// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(3),  // +
			shift(5),  // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(9),  // int
			shift(10), // float
			shift(12), // (
			nil,       // )
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // +
			nil,          // -
			nil,          // *
			nil,          // /
			nil,          // ^
			nil,          // **
			nil,          // int
			nil,          // float
			nil,          // (
			nil,          // )
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Calc
			shift(13), // +
			shift(14), // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(3),  // +
			shift(5),  // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(9),  // int
			shift(10), // float
			shift(12), // (
			nil,       // )
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // $, reduce: Expr0Lvl
			reduce(4), // +, reduce: Expr0Lvl
			reduce(4), // -, reduce: Expr0Lvl
			shift(16), // *
			shift(17), // /
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(3),  // +
			shift(5),  // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(9),  // int
			shift(10), // float
			shift(12), // (
			nil,       // )
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(7), // $, reduce: Expr1Lvl
			reduce(7), // +, reduce: Expr1Lvl
			reduce(7), // -, reduce: Expr1Lvl
			reduce(7), // *, reduce: Expr1Lvl
			reduce(7), // /, reduce: Expr1Lvl
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(10), // $, reduce: Expr2Lvl
			reduce(10), // +, reduce: Expr2Lvl
			reduce(10), // -, reduce: Expr2Lvl
			reduce(10), // *, reduce: Expr2Lvl
			reduce(10), // /, reduce: Expr2Lvl
			shift(19),  // ^
			shift(20),  // **
			nil,        // int
			nil,        // float
			nil,        // (
			nil,        // )
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(13), // $, reduce: Expr3Lvl
			reduce(13), // +, reduce: Expr3Lvl
			reduce(13), // -, reduce: Expr3Lvl
			reduce(13), // *, reduce: Expr3Lvl
			reduce(13), // /, reduce: Expr3Lvl
			reduce(13), // ^, reduce: Expr3Lvl
			reduce(13), // **, reduce: Expr3Lvl
			nil,        // int
			nil,        // float
			nil,        // (
			nil,        // )
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(14), // $, reduce: Number
			reduce(14), // +, reduce: Number
			reduce(14), // -, reduce: Number
			reduce(14), // *, reduce: Number
			reduce(14), // /, reduce: Number
			reduce(14), // ^, reduce: Number
			reduce(14), // **, reduce: Number
			nil,        // int
			nil,        // float
			nil,        // (
			nil,        // )
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(15), // $, reduce: Number
			reduce(15), // +, reduce: Number
			reduce(15), // -, reduce: Number
			reduce(15), // *, reduce: Number
			reduce(15), // /, reduce: Number
			reduce(15), // ^, reduce: Number
			reduce(15), // **, reduce: Number
			nil,        // int
			nil,        // float
			nil,        // (
			nil,        // )
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(16), // $, reduce: Number
			reduce(16), // +, reduce: Number
			reduce(16), // -, reduce: Number
			reduce(16), // *, reduce: Number
			reduce(16), // /, reduce: Number
			reduce(16), // ^, reduce: Number
			reduce(16), // **, reduce: Number
			nil,        // int
			nil,        // float
			nil,        // (
			nil,        // )
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // +
			shift(24), // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(28), // int
			shift(29), // float
			shift(31), // (
			nil,       // )
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(3),  // +
			shift(5),  // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(9),  // int
			shift(10), // float
			shift(12), // (
			nil,       // )
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(3),  // +
			shift(5),  // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(9),  // int
			shift(10), // float
			shift(12), // (
			nil,       // )
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(8), // $, reduce: Expr2Lvl
			reduce(8), // +, reduce: Expr2Lvl
			reduce(8), // -, reduce: Expr2Lvl
			reduce(8), // *, reduce: Expr2Lvl
			reduce(8), // /, reduce: Expr2Lvl
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(3),  // +
			shift(5),  // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(9),  // int
			shift(10), // float
			shift(12), // (
			nil,       // )
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(3),  // +
			shift(5),  // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(9),  // int
			shift(10), // float
			shift(12), // (
			nil,       // )
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(9), // $, reduce: Expr2Lvl
			reduce(9), // +, reduce: Expr2Lvl
			reduce(9), // -, reduce: Expr2Lvl
			reduce(9), // *, reduce: Expr2Lvl
			reduce(9), // /, reduce: Expr2Lvl
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(9),  // int
			shift(10), // float
			shift(12), // (
			nil,       // )
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(9),  // int
			shift(10), // float
			shift(12), // (
			nil,       // )
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(38), // +
			shift(39), // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			shift(40), // )
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // +
			shift(24), // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(28), // int
			shift(29), // float
			shift(31), // (
			nil,       // )
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(4), // +, reduce: Expr0Lvl
			reduce(4), // -, reduce: Expr0Lvl
			shift(42), // *
			shift(43), // /
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			reduce(4), // ), reduce: Expr0Lvl
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // +
			shift(24), // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(28), // int
			shift(29), // float
			shift(31), // (
			nil,       // )
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(7), // +, reduce: Expr1Lvl
			reduce(7), // -, reduce: Expr1Lvl
			reduce(7), // *, reduce: Expr1Lvl
			reduce(7), // /, reduce: Expr1Lvl
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			reduce(7), // ), reduce: Expr1Lvl
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(10), // +, reduce: Expr2Lvl
			reduce(10), // -, reduce: Expr2Lvl
			reduce(10), // *, reduce: Expr2Lvl
			reduce(10), // /, reduce: Expr2Lvl
			shift(45),  // ^
			shift(46),  // **
			nil,        // int
			nil,        // float
			nil,        // (
			reduce(10), // ), reduce: Expr2Lvl
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(13), // +, reduce: Expr3Lvl
			reduce(13), // -, reduce: Expr3Lvl
			reduce(13), // *, reduce: Expr3Lvl
			reduce(13), // /, reduce: Expr3Lvl
			reduce(13), // ^, reduce: Expr3Lvl
			reduce(13), // **, reduce: Expr3Lvl
			nil,        // int
			nil,        // float
			nil,        // (
			reduce(13), // ), reduce: Expr3Lvl
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(14), // +, reduce: Number
			reduce(14), // -, reduce: Number
			reduce(14), // *, reduce: Number
			reduce(14), // /, reduce: Number
			reduce(14), // ^, reduce: Number
			reduce(14), // **, reduce: Number
			nil,        // int
			nil,        // float
			nil,        // (
			reduce(14), // ), reduce: Number
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(15), // +, reduce: Number
			reduce(15), // -, reduce: Number
			reduce(15), // *, reduce: Number
			reduce(15), // /, reduce: Number
			reduce(15), // ^, reduce: Number
			reduce(15), // **, reduce: Number
			nil,        // int
			nil,        // float
			nil,        // (
			reduce(15), // ), reduce: Number
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(16), // +, reduce: Number
			reduce(16), // -, reduce: Number
			reduce(16), // *, reduce: Number
			reduce(16), // /, reduce: Number
			reduce(16), // ^, reduce: Number
			reduce(16), // **, reduce: Number
			nil,        // int
			nil,        // float
			nil,        // (
			reduce(16), // ), reduce: Number
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // +
			shift(24), // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(28), // int
			shift(29), // float
			shift(31), // (
			nil,       // )
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: Expr0Lvl
			reduce(2), // +, reduce: Expr0Lvl
			reduce(2), // -, reduce: Expr0Lvl
			shift(16), // *
			shift(17), // /
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: Expr0Lvl
			reduce(3), // +, reduce: Expr0Lvl
			reduce(3), // -, reduce: Expr0Lvl
			shift(16), // *
			shift(17), // /
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // $, reduce: Expr1Lvl
			reduce(5), // +, reduce: Expr1Lvl
			reduce(5), // -, reduce: Expr1Lvl
			reduce(5), // *, reduce: Expr1Lvl
			reduce(5), // /, reduce: Expr1Lvl
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // $, reduce: Expr1Lvl
			reduce(6), // +, reduce: Expr1Lvl
			reduce(6), // -, reduce: Expr1Lvl
			reduce(6), // *, reduce: Expr1Lvl
			reduce(6), // /, reduce: Expr1Lvl
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(11), // $, reduce: Expr3Lvl
			reduce(11), // +, reduce: Expr3Lvl
			reduce(11), // -, reduce: Expr3Lvl
			reduce(11), // *, reduce: Expr3Lvl
			reduce(11), // /, reduce: Expr3Lvl
			reduce(11), // ^, reduce: Expr3Lvl
			reduce(11), // **, reduce: Expr3Lvl
			nil,        // int
			nil,        // float
			nil,        // (
			nil,        // )
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(12), // $, reduce: Expr3Lvl
			reduce(12), // +, reduce: Expr3Lvl
			reduce(12), // -, reduce: Expr3Lvl
			reduce(12), // *, reduce: Expr3Lvl
			reduce(12), // /, reduce: Expr3Lvl
			reduce(12), // ^, reduce: Expr3Lvl
			reduce(12), // **, reduce: Expr3Lvl
			nil,        // int
			nil,        // float
			nil,        // (
			nil,        // )
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // +
			shift(24), // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(28), // int
			shift(29), // float
			shift(31), // (
			nil,       // )
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // +
			shift(24), // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(28), // int
			shift(29), // float
			shift(31), // (
			nil,       // )
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(17), // $, reduce: Bracket
			reduce(17), // +, reduce: Bracket
			reduce(17), // -, reduce: Bracket
			reduce(17), // *, reduce: Bracket
			reduce(17), // /, reduce: Bracket
			reduce(17), // ^, reduce: Bracket
			reduce(17), // **, reduce: Bracket
			nil,        // int
			nil,        // float
			nil,        // (
			nil,        // )
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(8), // +, reduce: Expr2Lvl
			reduce(8), // -, reduce: Expr2Lvl
			reduce(8), // *, reduce: Expr2Lvl
			reduce(8), // /, reduce: Expr2Lvl
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			reduce(8), // ), reduce: Expr2Lvl
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // +
			shift(24), // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(28), // int
			shift(29), // float
			shift(31), // (
			nil,       // )
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(22), // +
			shift(24), // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(28), // int
			shift(29), // float
			shift(31), // (
			nil,       // )
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(9), // +, reduce: Expr2Lvl
			reduce(9), // -, reduce: Expr2Lvl
			reduce(9), // *, reduce: Expr2Lvl
			reduce(9), // /, reduce: Expr2Lvl
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			reduce(9), // ), reduce: Expr2Lvl
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(28), // int
			shift(29), // float
			shift(31), // (
			nil,       // )
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // +
			nil,       // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			shift(28), // int
			shift(29), // float
			shift(31), // (
			nil,       // )
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(38), // +
			shift(39), // -
			nil,       // *
			nil,       // /
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			shift(54), // )
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(2), // +, reduce: Expr0Lvl
			reduce(2), // -, reduce: Expr0Lvl
			shift(42), // *
			shift(43), // /
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			reduce(2), // ), reduce: Expr0Lvl
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(3), // +, reduce: Expr0Lvl
			reduce(3), // -, reduce: Expr0Lvl
			shift(42), // *
			shift(43), // /
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			reduce(3), // ), reduce: Expr0Lvl
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(5), // +, reduce: Expr1Lvl
			reduce(5), // -, reduce: Expr1Lvl
			reduce(5), // *, reduce: Expr1Lvl
			reduce(5), // /, reduce: Expr1Lvl
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			reduce(5), // ), reduce: Expr1Lvl
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(6), // +, reduce: Expr1Lvl
			reduce(6), // -, reduce: Expr1Lvl
			reduce(6), // *, reduce: Expr1Lvl
			reduce(6), // /, reduce: Expr1Lvl
			nil,       // ^
			nil,       // **
			nil,       // int
			nil,       // float
			nil,       // (
			reduce(6), // ), reduce: Expr1Lvl
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(11), // +, reduce: Expr3Lvl
			reduce(11), // -, reduce: Expr3Lvl
			reduce(11), // *, reduce: Expr3Lvl
			reduce(11), // /, reduce: Expr3Lvl
			reduce(11), // ^, reduce: Expr3Lvl
			reduce(11), // **, reduce: Expr3Lvl
			nil,        // int
			nil,        // float
			nil,        // (
			reduce(11), // ), reduce: Expr3Lvl
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(12), // +, reduce: Expr3Lvl
			reduce(12), // -, reduce: Expr3Lvl
			reduce(12), // *, reduce: Expr3Lvl
			reduce(12), // /, reduce: Expr3Lvl
			reduce(12), // ^, reduce: Expr3Lvl
			reduce(12), // **, reduce: Expr3Lvl
			nil,        // int
			nil,        // float
			nil,        // (
			reduce(12), // ), reduce: Expr3Lvl
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(17), // +, reduce: Bracket
			reduce(17), // -, reduce: Bracket
			reduce(17), // *, reduce: Bracket
			reduce(17), // /, reduce: Bracket
			reduce(17), // ^, reduce: Bracket
			reduce(17), // **, reduce: Bracket
			nil,        // int
			nil,        // float
			nil,        // (
			reduce(17), // ), reduce: Bracket
		},
	},
}
