// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 8

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Calc
		2,  // Expr0Lvl
		4,  // Expr1Lvl
		6,  // Expr2Lvl
		7,  // Expr3Lvl
		8,  // Number
		11, // Bracket
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		15, // Expr2Lvl
		7,  // Expr3Lvl
		8,  // Number
		11, // Bracket
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		18, // Expr2Lvl
		7,  // Expr3Lvl
		8,  // Number
		11, // Bracket
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Calc
		21, // Expr0Lvl
		23, // Expr1Lvl
		25, // Expr2Lvl
		26, // Expr3Lvl
		27, // Number
		30, // Bracket
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		32, // Expr1Lvl
		6,  // Expr2Lvl
		7,  // Expr3Lvl
		8,  // Number
		11, // Bracket
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		33, // Expr1Lvl
		6,  // Expr2Lvl
		7,  // Expr3Lvl
		8,  // Number
		11, // Bracket
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		34, // Expr2Lvl
		7,  // Expr3Lvl
		8,  // Number
		11, // Bracket
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		35, // Expr2Lvl
		7,  // Expr3Lvl
		8,  // Number
		11, // Bracket
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		36, // Number
		11, // Bracket
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		37, // Number
		11, // Bracket
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		41, // Expr2Lvl
		26, // Expr3Lvl
		27, // Number
		30, // Bracket
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		44, // Expr2Lvl
		26, // Expr3Lvl
		27, // Number
		30, // Bracket
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Calc
		47, // Expr0Lvl
		23, // Expr1Lvl
		25, // Expr2Lvl
		26, // Expr3Lvl
		27, // Number
		30, // Bracket
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		48, // Expr1Lvl
		25, // Expr2Lvl
		26, // Expr3Lvl
		27, // Number
		30, // Bracket
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		49, // Expr1Lvl
		25, // Expr2Lvl
		26, // Expr3Lvl
		27, // Number
		30, // Bracket
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		50, // Expr2Lvl
		26, // Expr3Lvl
		27, // Number
		30, // Bracket
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		51, // Expr2Lvl
		26, // Expr3Lvl
		27, // Number
		30, // Bracket
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S45
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		52, // Number
		30, // Bracket
	},
	gotoRow{ // S46
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		53, // Number
		30, // Bracket
	},
	gotoRow{ // S47
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S48
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S49
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S50
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S51
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S52
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S53
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S54
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
		-1, // Number
		-1, // Bracket
	},
}
