// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 7

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Calc
		2,  // Expr0Lvl
		4,  // Expr1Lvl
		6,  // Expr2Lvl
		7,  // Number
		9,  // Bracket
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		13, // Expr2Lvl
		7,  // Number
		9,  // Bracket
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		16, // Expr2Lvl
		7,  // Number
		9,  // Bracket
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Calc
		17, // Expr0Lvl
		19, // Expr1Lvl
		21, // Expr2Lvl
		22, // Number
		24, // Bracket
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		26, // Expr1Lvl
		6,  // Expr2Lvl
		7,  // Number
		9,  // Bracket
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		27, // Expr1Lvl
		6,  // Expr2Lvl
		7,  // Number
		9,  // Bracket
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		28, // Expr2Lvl
		7,  // Number
		9,  // Bracket
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		29, // Expr2Lvl
		7,  // Number
		9,  // Bracket
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		33, // Expr2Lvl
		22, // Number
		24, // Bracket
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		36, // Expr2Lvl
		22, // Number
		24, // Bracket
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Calc
		37, // Expr0Lvl
		19, // Expr1Lvl
		21, // Expr2Lvl
		22, // Number
		24, // Bracket
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		38, // Expr1Lvl
		21, // Expr2Lvl
		22, // Number
		24, // Bracket
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		39, // Expr1Lvl
		21, // Expr2Lvl
		22, // Number
		24, // Bracket
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		40, // Expr2Lvl
		22, // Number
		24, // Bracket
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		41, // Expr2Lvl
		22, // Number
		24, // Bracket
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Number
		-1, // Bracket
	},
}
