// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 6

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Calc
		2,  // Expr0Lvl
		4,  // Expr1Lvl
		6,  // Expr2Lvl
		7,  // Expr3Lvl
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		12, // Expr2Lvl
		7,  // Expr3Lvl
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		15, // Expr2Lvl
		7,  // Expr3Lvl
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Calc
		16, // Expr0Lvl
		18, // Expr1Lvl
		20, // Expr2Lvl
		21, // Expr3Lvl
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		24, // Expr1Lvl
		6,  // Expr2Lvl
		7,  // Expr3Lvl
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		25, // Expr1Lvl
		6,  // Expr2Lvl
		7,  // Expr3Lvl
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		26, // Expr2Lvl
		7,  // Expr3Lvl
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		27, // Expr2Lvl
		7,  // Expr3Lvl
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		31, // Expr2Lvl
		21, // Expr3Lvl
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		34, // Expr2Lvl
		21, // Expr3Lvl
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Calc
		35, // Expr0Lvl
		18, // Expr1Lvl
		20, // Expr2Lvl
		21, // Expr3Lvl
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		36, // Expr1Lvl
		20, // Expr2Lvl
		21, // Expr3Lvl
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		37, // Expr1Lvl
		20, // Expr2Lvl
		21, // Expr3Lvl
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		38, // Expr2Lvl
		21, // Expr3Lvl
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		39, // Expr2Lvl
		21, // Expr3Lvl
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Calc
		-1, // Expr0Lvl
		-1, // Expr1Lvl
		-1, // Expr2Lvl
		-1, // Expr3Lvl
	},
}
