// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: proto/runify.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RunifyClient is the client API for Runify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunifyClient interface {
	ServiceChannel(ctx context.Context, opts ...grpc.CallOption) (Runify_ServiceChannelClient, error)
	FormDataChannel(ctx context.Context, opts ...grpc.CallOption) (Runify_FormDataChannelClient, error)
	GetRoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Form, error)
	GetActions(ctx context.Context, in *SelectedCard, opts ...grpc.CallOption) (*Actions, error)
	ExecuteDefault(ctx context.Context, in *SelectedCard, opts ...grpc.CallOption) (*Result, error)
	Execute(ctx context.Context, in *SelectedAction, opts ...grpc.CallOption) (*Result, error)
}

type runifyClient struct {
	cc grpc.ClientConnInterface
}

func NewRunifyClient(cc grpc.ClientConnInterface) RunifyClient {
	return &runifyClient{cc}
}

func (c *runifyClient) ServiceChannel(ctx context.Context, opts ...grpc.CallOption) (Runify_ServiceChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &Runify_ServiceDesc.Streams[0], "/runify.Runify/ServiceChannel", opts...)
	if err != nil {
		return nil, err
	}
	x := &runifyServiceChannelClient{stream}
	return x, nil
}

type Runify_ServiceChannelClient interface {
	Send(*ServiceMsgUI) error
	Recv() (*ServiceMsgSrv, error)
	grpc.ClientStream
}

type runifyServiceChannelClient struct {
	grpc.ClientStream
}

func (x *runifyServiceChannelClient) Send(m *ServiceMsgUI) error {
	return x.ClientStream.SendMsg(m)
}

func (x *runifyServiceChannelClient) Recv() (*ServiceMsgSrv, error) {
	m := new(ServiceMsgSrv)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *runifyClient) FormDataChannel(ctx context.Context, opts ...grpc.CallOption) (Runify_FormDataChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &Runify_ServiceDesc.Streams[1], "/runify.Runify/FormDataChannel", opts...)
	if err != nil {
		return nil, err
	}
	x := &runifyFormDataChannelClient{stream}
	return x, nil
}

type Runify_FormDataChannelClient interface {
	Send(*FormDataMsgUI) error
	Recv() (*FormDataMsgSrv, error)
	grpc.ClientStream
}

type runifyFormDataChannelClient struct {
	grpc.ClientStream
}

func (x *runifyFormDataChannelClient) Send(m *FormDataMsgUI) error {
	return x.ClientStream.SendMsg(m)
}

func (x *runifyFormDataChannelClient) Recv() (*FormDataMsgSrv, error) {
	m := new(FormDataMsgSrv)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *runifyClient) GetRoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Form, error) {
	out := new(Form)
	err := c.cc.Invoke(ctx, "/runify.Runify/GetRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runifyClient) GetActions(ctx context.Context, in *SelectedCard, opts ...grpc.CallOption) (*Actions, error) {
	out := new(Actions)
	err := c.cc.Invoke(ctx, "/runify.Runify/GetActions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runifyClient) ExecuteDefault(ctx context.Context, in *SelectedCard, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/runify.Runify/ExecuteDefault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runifyClient) Execute(ctx context.Context, in *SelectedAction, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/runify.Runify/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunifyServer is the server API for Runify service.
// All implementations must embed UnimplementedRunifyServer
// for forward compatibility
type RunifyServer interface {
	ServiceChannel(Runify_ServiceChannelServer) error
	FormDataChannel(Runify_FormDataChannelServer) error
	GetRoot(context.Context, *Empty) (*Form, error)
	GetActions(context.Context, *SelectedCard) (*Actions, error)
	ExecuteDefault(context.Context, *SelectedCard) (*Result, error)
	Execute(context.Context, *SelectedAction) (*Result, error)
	mustEmbedUnimplementedRunifyServer()
}

// UnimplementedRunifyServer must be embedded to have forward compatible implementations.
type UnimplementedRunifyServer struct {
}

func (UnimplementedRunifyServer) ServiceChannel(Runify_ServiceChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method ServiceChannel not implemented")
}
func (UnimplementedRunifyServer) FormDataChannel(Runify_FormDataChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method FormDataChannel not implemented")
}
func (UnimplementedRunifyServer) GetRoot(context.Context, *Empty) (*Form, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoot not implemented")
}
func (UnimplementedRunifyServer) GetActions(context.Context, *SelectedCard) (*Actions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActions not implemented")
}
func (UnimplementedRunifyServer) ExecuteDefault(context.Context, *SelectedCard) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteDefault not implemented")
}
func (UnimplementedRunifyServer) Execute(context.Context, *SelectedAction) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedRunifyServer) mustEmbedUnimplementedRunifyServer() {}

// UnsafeRunifyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunifyServer will
// result in compilation errors.
type UnsafeRunifyServer interface {
	mustEmbedUnimplementedRunifyServer()
}

func RegisterRunifyServer(s grpc.ServiceRegistrar, srv RunifyServer) {
	s.RegisterService(&Runify_ServiceDesc, srv)
}

func _Runify_ServiceChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RunifyServer).ServiceChannel(&runifyServiceChannelServer{stream})
}

type Runify_ServiceChannelServer interface {
	Send(*ServiceMsgSrv) error
	Recv() (*ServiceMsgUI, error)
	grpc.ServerStream
}

type runifyServiceChannelServer struct {
	grpc.ServerStream
}

func (x *runifyServiceChannelServer) Send(m *ServiceMsgSrv) error {
	return x.ServerStream.SendMsg(m)
}

func (x *runifyServiceChannelServer) Recv() (*ServiceMsgUI, error) {
	m := new(ServiceMsgUI)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Runify_FormDataChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RunifyServer).FormDataChannel(&runifyFormDataChannelServer{stream})
}

type Runify_FormDataChannelServer interface {
	Send(*FormDataMsgSrv) error
	Recv() (*FormDataMsgUI, error)
	grpc.ServerStream
}

type runifyFormDataChannelServer struct {
	grpc.ServerStream
}

func (x *runifyFormDataChannelServer) Send(m *FormDataMsgSrv) error {
	return x.ServerStream.SendMsg(m)
}

func (x *runifyFormDataChannelServer) Recv() (*FormDataMsgUI, error) {
	m := new(FormDataMsgUI)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Runify_GetRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunifyServer).GetRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runify.Runify/GetRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunifyServer).GetRoot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runify_GetActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectedCard)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunifyServer).GetActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runify.Runify/GetActions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunifyServer).GetActions(ctx, req.(*SelectedCard))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runify_ExecuteDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectedCard)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunifyServer).ExecuteDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runify.Runify/ExecuteDefault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunifyServer).ExecuteDefault(ctx, req.(*SelectedCard))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runify_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectedAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunifyServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runify.Runify/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunifyServer).Execute(ctx, req.(*SelectedAction))
	}
	return interceptor(ctx, in, info, handler)
}

// Runify_ServiceDesc is the grpc.ServiceDesc for Runify service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runify_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runify.Runify",
	HandlerType: (*RunifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoot",
			Handler:    _Runify_GetRoot_Handler,
		},
		{
			MethodName: "GetActions",
			Handler:    _Runify_GetActions_Handler,
		},
		{
			MethodName: "ExecuteDefault",
			Handler:    _Runify_ExecuteDefault_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Runify_Execute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServiceChannel",
			Handler:       _Runify_ServiceChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "FormDataChannel",
			Handler:       _Runify_FormDataChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/runify.proto",
}
