// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: proto/runify.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_DEBUG   LogLevel = 0
	LogLevel_INFO    LogLevel = 1
	LogLevel_WARNING LogLevel = 2
	LogLevel_ERROR   LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "DEBUG",
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
	}
	LogLevel_value = map[string]int32{
		"DEBUG":   0,
		"INFO":    1,
		"WARNING": 2,
		"ERROR":   3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runify_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_runify_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{0}
}

type FormStateType int32

const (
	FormStateType_SHOW FormStateType = 0
	FormStateType_HIDE FormStateType = 1
)

// Enum value maps for FormStateType.
var (
	FormStateType_name = map[int32]string{
		0: "SHOW",
		1: "HIDE",
	}
	FormStateType_value = map[string]int32{
		"SHOW": 0,
		"HIDE": 1,
	}
)

func (x FormStateType) Enum() *FormStateType {
	p := new(FormStateType)
	*p = x
	return p
}

func (x FormStateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormStateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runify_proto_enumTypes[1].Descriptor()
}

func (FormStateType) Type() protoreflect.EnumType {
	return &file_proto_runify_proto_enumTypes[1]
}

func (x FormStateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormStateType.Descriptor instead.
func (FormStateType) EnumDescriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{1}
}

type MessageType int32

const (
	MessageType_TYPE_ERROR MessageType = 0
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TYPE_ERROR",
	}
	MessageType_value = map[string]int32{
		"TYPE_ERROR": 0,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runify_proto_enumTypes[2].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_runify_proto_enumTypes[2]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{2}
}

type FormActionType int32

const (
	FormActionType_CLOSE_ALL    FormActionType = 0
	FormActionType_CLOSE_ONE    FormActionType = 1
	FormActionType_SHOW_MESSAGE FormActionType = 2
)

// Enum value maps for FormActionType.
var (
	FormActionType_name = map[int32]string{
		0: "CLOSE_ALL",
		1: "CLOSE_ONE",
		2: "SHOW_MESSAGE",
	}
	FormActionType_value = map[string]int32{
		"CLOSE_ALL":    0,
		"CLOSE_ONE":    1,
		"SHOW_MESSAGE": 2,
	}
)

func (x FormActionType) Enum() *FormActionType {
	p := new(FormActionType)
	*p = x
	return p
}

func (x FormActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runify_proto_enumTypes[3].Descriptor()
}

func (FormActionType) Type() protoreflect.EnumType {
	return &file_proto_runify_proto_enumTypes[3]
}

func (x FormActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormActionType.Descriptor instead.
func (FormActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{3}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{0}
}

type CardItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardID uint64 `protobuf:"varint,1,opt,name=cardID,proto3" json:"cardID,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon   string `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
}

func (x *CardItem) Reset() {
	*x = CardItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardItem) ProtoMessage() {}

func (x *CardItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardItem.ProtoReflect.Descriptor instead.
func (*CardItem) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{1}
}

func (x *CardItem) GetCardID() uint64 {
	if x != nil {
		return x.CardID
	}
	return 0
}

func (x *CardItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CardItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type SelectedCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardID uint64 `protobuf:"varint,1,opt,name=cardID,proto3" json:"cardID,omitempty"`
}

func (x *SelectedCard) Reset() {
	*x = SelectedCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectedCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedCard) ProtoMessage() {}

func (x *SelectedCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedCard.ProtoReflect.Descriptor instead.
func (*SelectedCard) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{2}
}

func (x *SelectedCard) GetCardID() uint64 {
	if x != nil {
		return x.CardID
	}
	return 0
}

type ActionItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionID uint32 `protobuf:"varint,1,opt,name=actionID,proto3" json:"actionID,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ActionItem) Reset() {
	*x = ActionItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionItem) ProtoMessage() {}

func (x *ActionItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionItem.ProtoReflect.Descriptor instead.
func (*ActionItem) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{3}
}

func (x *ActionItem) GetActionID() uint32 {
	if x != nil {
		return x.ActionID
	}
	return 0
}

func (x *ActionItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Actions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ActionItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Actions) Reset() {
	*x = Actions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Actions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actions) ProtoMessage() {}

func (x *Actions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actions.ProtoReflect.Descriptor instead.
func (*Actions) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{4}
}

func (x *Actions) GetItems() []*ActionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SelectedAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionID uint32 `protobuf:"varint,1,opt,name=actionID,proto3" json:"actionID,omitempty"`
	CardID   uint64 `protobuf:"varint,2,opt,name=cardID,proto3" json:"cardID,omitempty"`
}

func (x *SelectedAction) Reset() {
	*x = SelectedAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectedAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedAction) ProtoMessage() {}

func (x *SelectedAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedAction.ProtoReflect.Descriptor instead.
func (*SelectedAction) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{5}
}

func (x *SelectedAction) GetActionID() uint32 {
	if x != nil {
		return x.ActionID
	}
	return 0
}

func (x *SelectedAction) GetCardID() uint64 {
	if x != nil {
		return x.CardID
	}
	return 0
}

type Form struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layout string      `protobuf:"bytes,1,opt,name=layout,proto3" json:"layout,omitempty"`
	Cards  []*CardItem `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *Form) Reset() {
	*x = Form{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Form) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Form) ProtoMessage() {}

func (x *Form) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Form.ProtoReflect.Descriptor instead.
func (*Form) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{6}
}

func (x *Form) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

func (x *Form) GetCards() []*CardItem {
	if x != nil {
		return x.Cards
	}
	return nil
}

type HideWindow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *HideWindow) Reset() {
	*x = HideWindow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HideWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HideWindow) ProtoMessage() {}

func (x *HideWindow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HideWindow.ProtoReflect.Descriptor instead.
func (*HideWindow) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{7}
}

func (x *HideWindow) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*Result_Form
	//	*Result_Empty
	//	*Result_Hide
	Payload isResult_Payload `protobuf_oneof:"payload"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{8}
}

func (m *Result) GetPayload() isResult_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Result) GetForm() *Form {
	if x, ok := x.GetPayload().(*Result_Form); ok {
		return x.Form
	}
	return nil
}

func (x *Result) GetEmpty() *Empty {
	if x, ok := x.GetPayload().(*Result_Empty); ok {
		return x.Empty
	}
	return nil
}

func (x *Result) GetHide() *HideWindow {
	if x, ok := x.GetPayload().(*Result_Hide); ok {
		return x.Hide
	}
	return nil
}

type isResult_Payload interface {
	isResult_Payload()
}

type Result_Form struct {
	Form *Form `protobuf:"bytes,1,opt,name=form,proto3,oneof"`
}

type Result_Empty struct {
	Empty *Empty `protobuf:"bytes,2,opt,name=empty,proto3,oneof"`
}

type Result_Hide struct {
	Hide *HideWindow `protobuf:"bytes,3,opt,name=hide,proto3,oneof"`
}

func (*Result_Form) isResult_Payload() {}

func (*Result_Empty) isResult_Payload() {}

func (*Result_Hide) isResult_Payload() {}

type WriteLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level   LogLevel `protobuf:"varint,1,opt,name=level,proto3,enum=runify.LogLevel" json:"level,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WriteLog) Reset() {
	*x = WriteLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteLog) ProtoMessage() {}

func (x *WriteLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteLog.ProtoReflect.Descriptor instead.
func (*WriteLog) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{9}
}

func (x *WriteLog) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_DEBUG
}

func (x *WriteLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SetFormState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State FormStateType `protobuf:"varint,1,opt,name=state,proto3,enum=runify.FormStateType" json:"state,omitempty"`
}

func (x *SetFormState) Reset() {
	*x = SetFormState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetFormState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFormState) ProtoMessage() {}

func (x *SetFormState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFormState.ProtoReflect.Descriptor instead.
func (*SetFormState) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{10}
}

func (x *SetFormState) GetState() FormStateType {
	if x != nil {
		return x.State
	}
	return FormStateType_SHOW
}

type ServiceMsgUI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ServiceMsgUI_WriteLog
	Payload isServiceMsgUI_Payload `protobuf_oneof:"payload"`
}

func (x *ServiceMsgUI) Reset() {
	*x = ServiceMsgUI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceMsgUI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMsgUI) ProtoMessage() {}

func (x *ServiceMsgUI) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMsgUI.ProtoReflect.Descriptor instead.
func (*ServiceMsgUI) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{11}
}

func (m *ServiceMsgUI) GetPayload() isServiceMsgUI_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ServiceMsgUI) GetWriteLog() *WriteLog {
	if x, ok := x.GetPayload().(*ServiceMsgUI_WriteLog); ok {
		return x.WriteLog
	}
	return nil
}

type isServiceMsgUI_Payload interface {
	isServiceMsgUI_Payload()
}

type ServiceMsgUI_WriteLog struct {
	WriteLog *WriteLog `protobuf:"bytes,1,opt,name=writeLog,proto3,oneof"`
}

func (*ServiceMsgUI_WriteLog) isServiceMsgUI_Payload() {}

type ServiceMsgSrv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ServiceMsgSrv_SetFormState
	Payload isServiceMsgSrv_Payload `protobuf_oneof:"payload"`
}

func (x *ServiceMsgSrv) Reset() {
	*x = ServiceMsgSrv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceMsgSrv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMsgSrv) ProtoMessage() {}

func (x *ServiceMsgSrv) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMsgSrv.ProtoReflect.Descriptor instead.
func (*ServiceMsgSrv) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{12}
}

func (m *ServiceMsgSrv) GetPayload() isServiceMsgSrv_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ServiceMsgSrv) GetSetFormState() *SetFormState {
	if x, ok := x.GetPayload().(*ServiceMsgSrv_SetFormState); ok {
		return x.SetFormState
	}
	return nil
}

type isServiceMsgSrv_Payload interface {
	isServiceMsgSrv_Payload()
}

type ServiceMsgSrv_SetFormState struct {
	SetFormState *SetFormState `protobuf:"bytes,1,opt,name=setFormState,proto3,oneof"`
}

func (*ServiceMsgSrv_SetFormState) isServiceMsgSrv_Payload() {}

type RootListRowGlobalID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderID uint32 `protobuf:"varint,1,opt,name=providerID,proto3" json:"providerID,omitempty"`
	RowID      uint32 `protobuf:"varint,2,opt,name=rowID,proto3" json:"rowID,omitempty"`
}

func (x *RootListRowGlobalID) Reset() {
	*x = RootListRowGlobalID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootListRowGlobalID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootListRowGlobalID) ProtoMessage() {}

func (x *RootListRowGlobalID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootListRowGlobalID.ProtoReflect.Descriptor instead.
func (*RootListRowGlobalID) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{13}
}

func (x *RootListRowGlobalID) GetProviderID() uint32 {
	if x != nil {
		return x.ProviderID
	}
	return 0
}

func (x *RootListRowGlobalID) GetRowID() uint32 {
	if x != nil {
		return x.RowID
	}
	return 0
}

type RootListRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderID uint32 `protobuf:"varint,1,opt,name=providerID,proto3" json:"providerID,omitempty"`
	RowID      uint32 `protobuf:"varint,2,opt,name=rowID,proto3" json:"rowID,omitempty"`
	Priority   uint32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Icon       string `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Value      string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RootListRow) Reset() {
	*x = RootListRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootListRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootListRow) ProtoMessage() {}

func (x *RootListRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootListRow.ProtoReflect.Descriptor instead.
func (*RootListRow) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{14}
}

func (x *RootListRow) GetProviderID() uint32 {
	if x != nil {
		return x.ProviderID
	}
	return 0
}

func (x *RootListRow) GetRowID() uint32 {
	if x != nil {
		return x.RowID
	}
	return 0
}

func (x *RootListRow) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RootListRow) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *RootListRow) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RootListOpen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*RootListRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *RootListOpen) Reset() {
	*x = RootListOpen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootListOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootListOpen) ProtoMessage() {}

func (x *RootListOpen) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootListOpen.ProtoReflect.Descriptor instead.
func (*RootListOpen) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{15}
}

func (x *RootListOpen) GetRows() []*RootListRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type RootListAddRows struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*RootListRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *RootListAddRows) Reset() {
	*x = RootListAddRows{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootListAddRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootListAddRows) ProtoMessage() {}

func (x *RootListAddRows) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootListAddRows.ProtoReflect.Descriptor instead.
func (*RootListAddRows) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{16}
}

func (x *RootListAddRows) GetRows() []*RootListRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type RootListChangeRows struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*RootListRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *RootListChangeRows) Reset() {
	*x = RootListChangeRows{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootListChangeRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootListChangeRows) ProtoMessage() {}

func (x *RootListChangeRows) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootListChangeRows.ProtoReflect.Descriptor instead.
func (*RootListChangeRows) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{17}
}

func (x *RootListChangeRows) GetRows() []*RootListRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type RootListRemoveRows struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*RootListRowGlobalID `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *RootListRemoveRows) Reset() {
	*x = RootListRemoveRows{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootListRemoveRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootListRemoveRows) ProtoMessage() {}

func (x *RootListRemoveRows) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootListRemoveRows.ProtoReflect.Descriptor instead.
func (*RootListRemoveRows) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{18}
}

func (x *RootListRemoveRows) GetRows() []*RootListRowGlobalID {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ContextMenuRowID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RowID uint32 `protobuf:"varint,1,opt,name=rowID,proto3" json:"rowID,omitempty"`
}

func (x *ContextMenuRowID) Reset() {
	*x = ContextMenuRowID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContextMenuRowID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextMenuRowID) ProtoMessage() {}

func (x *ContextMenuRowID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextMenuRowID.ProtoReflect.Descriptor instead.
func (*ContextMenuRowID) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{19}
}

func (x *ContextMenuRowID) GetRowID() uint32 {
	if x != nil {
		return x.RowID
	}
	return 0
}

type FormClosed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FormClosed) Reset() {
	*x = FormClosed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormClosed) ProtoMessage() {}

func (x *FormClosed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormClosed.ProtoReflect.Descriptor instead.
func (*FormClosed) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{20}
}

type ContextMenuRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RowID uint32 `protobuf:"varint,1,opt,name=rowID,proto3" json:"rowID,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ContextMenuRow) Reset() {
	*x = ContextMenuRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContextMenuRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextMenuRow) ProtoMessage() {}

func (x *ContextMenuRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextMenuRow.ProtoReflect.Descriptor instead.
func (*ContextMenuRow) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{21}
}

func (x *ContextMenuRow) GetRowID() uint32 {
	if x != nil {
		return x.RowID
	}
	return 0
}

func (x *ContextMenuRow) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ContextMenuOpen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*ContextMenuRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *ContextMenuOpen) Reset() {
	*x = ContextMenuOpen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContextMenuOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextMenuOpen) ProtoMessage() {}

func (x *ContextMenuOpen) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextMenuOpen.ProtoReflect.Descriptor instead.
func (*ContextMenuOpen) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{22}
}

func (x *ContextMenuOpen) GetRows() []*ContextMenuRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type UserMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=runify.MessageType" json:"messageType,omitempty"`
	Message     string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{23}
}

func (x *UserMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_TYPE_ERROR
}

func (x *UserMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FormAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionType FormActionType `protobuf:"varint,1,opt,name=actionType,proto3,enum=runify.FormActionType" json:"actionType,omitempty"`
	Message    *UserMessage   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *FormAction) Reset() {
	*x = FormAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormAction) ProtoMessage() {}

func (x *FormAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormAction.ProtoReflect.Descriptor instead.
func (*FormAction) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{24}
}

func (x *FormAction) GetActionType() FormActionType {
	if x != nil {
		return x.ActionType
	}
	return FormActionType_CLOSE_ALL
}

func (x *FormAction) GetMessage() *UserMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type FilterData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FilterData) Reset() {
	*x = FilterData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterData) ProtoMessage() {}

func (x *FilterData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterData.ProtoReflect.Descriptor instead.
func (*FilterData) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{25}
}

func (x *FilterData) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FormDataMsgUI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormID uint32 `protobuf:"varint,1,opt,name=formID,proto3" json:"formID,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*FormDataMsgUI_FilterChanged
	//	*FormDataMsgUI_RootListRowActivated
	//	*FormDataMsgUI_RootListMenuActivated
	//	*FormDataMsgUI_ContextMenuRowActivated
	//	*FormDataMsgUI_FormClosed
	Payload isFormDataMsgUI_Payload `protobuf_oneof:"payload"`
}

func (x *FormDataMsgUI) Reset() {
	*x = FormDataMsgUI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormDataMsgUI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormDataMsgUI) ProtoMessage() {}

func (x *FormDataMsgUI) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormDataMsgUI.ProtoReflect.Descriptor instead.
func (*FormDataMsgUI) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{26}
}

func (x *FormDataMsgUI) GetFormID() uint32 {
	if x != nil {
		return x.FormID
	}
	return 0
}

func (m *FormDataMsgUI) GetPayload() isFormDataMsgUI_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *FormDataMsgUI) GetFilterChanged() *FilterData {
	if x, ok := x.GetPayload().(*FormDataMsgUI_FilterChanged); ok {
		return x.FilterChanged
	}
	return nil
}

func (x *FormDataMsgUI) GetRootListRowActivated() *RootListRowGlobalID {
	if x, ok := x.GetPayload().(*FormDataMsgUI_RootListRowActivated); ok {
		return x.RootListRowActivated
	}
	return nil
}

func (x *FormDataMsgUI) GetRootListMenuActivated() *RootListRowGlobalID {
	if x, ok := x.GetPayload().(*FormDataMsgUI_RootListMenuActivated); ok {
		return x.RootListMenuActivated
	}
	return nil
}

func (x *FormDataMsgUI) GetContextMenuRowActivated() *ContextMenuRowID {
	if x, ok := x.GetPayload().(*FormDataMsgUI_ContextMenuRowActivated); ok {
		return x.ContextMenuRowActivated
	}
	return nil
}

func (x *FormDataMsgUI) GetFormClosed() *FormClosed {
	if x, ok := x.GetPayload().(*FormDataMsgUI_FormClosed); ok {
		return x.FormClosed
	}
	return nil
}

type isFormDataMsgUI_Payload interface {
	isFormDataMsgUI_Payload()
}

type FormDataMsgUI_FilterChanged struct {
	FilterChanged *FilterData `protobuf:"bytes,2,opt,name=filterChanged,proto3,oneof"`
}

type FormDataMsgUI_RootListRowActivated struct {
	RootListRowActivated *RootListRowGlobalID `protobuf:"bytes,3,opt,name=rootListRowActivated,proto3,oneof"`
}

type FormDataMsgUI_RootListMenuActivated struct {
	RootListMenuActivated *RootListRowGlobalID `protobuf:"bytes,4,opt,name=rootListMenuActivated,proto3,oneof"`
}

type FormDataMsgUI_ContextMenuRowActivated struct {
	ContextMenuRowActivated *ContextMenuRowID `protobuf:"bytes,5,opt,name=contextMenuRowActivated,proto3,oneof"`
}

type FormDataMsgUI_FormClosed struct {
	FormClosed *FormClosed `protobuf:"bytes,6,opt,name=formClosed,proto3,oneof"`
}

func (*FormDataMsgUI_FilterChanged) isFormDataMsgUI_Payload() {}

func (*FormDataMsgUI_RootListRowActivated) isFormDataMsgUI_Payload() {}

func (*FormDataMsgUI_RootListMenuActivated) isFormDataMsgUI_Payload() {}

func (*FormDataMsgUI_ContextMenuRowActivated) isFormDataMsgUI_Payload() {}

func (*FormDataMsgUI_FormClosed) isFormDataMsgUI_Payload() {}

type FormDataMsgSrv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormID uint32 `protobuf:"varint,1,opt,name=formID,proto3" json:"formID,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*FormDataMsgSrv_RootListOpen
	//	*FormDataMsgSrv_RootListAddRows
	//	*FormDataMsgSrv_RootListChangeRows
	//	*FormDataMsgSrv_RootListRemoveRows
	//	*FormDataMsgSrv_ContextMenuOpen
	//	*FormDataMsgSrv_FormAction
	Payload isFormDataMsgSrv_Payload `protobuf_oneof:"payload"`
}

func (x *FormDataMsgSrv) Reset() {
	*x = FormDataMsgSrv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_runify_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormDataMsgSrv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormDataMsgSrv) ProtoMessage() {}

func (x *FormDataMsgSrv) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runify_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormDataMsgSrv.ProtoReflect.Descriptor instead.
func (*FormDataMsgSrv) Descriptor() ([]byte, []int) {
	return file_proto_runify_proto_rawDescGZIP(), []int{27}
}

func (x *FormDataMsgSrv) GetFormID() uint32 {
	if x != nil {
		return x.FormID
	}
	return 0
}

func (m *FormDataMsgSrv) GetPayload() isFormDataMsgSrv_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *FormDataMsgSrv) GetRootListOpen() *RootListOpen {
	if x, ok := x.GetPayload().(*FormDataMsgSrv_RootListOpen); ok {
		return x.RootListOpen
	}
	return nil
}

func (x *FormDataMsgSrv) GetRootListAddRows() *RootListAddRows {
	if x, ok := x.GetPayload().(*FormDataMsgSrv_RootListAddRows); ok {
		return x.RootListAddRows
	}
	return nil
}

func (x *FormDataMsgSrv) GetRootListChangeRows() *RootListChangeRows {
	if x, ok := x.GetPayload().(*FormDataMsgSrv_RootListChangeRows); ok {
		return x.RootListChangeRows
	}
	return nil
}

func (x *FormDataMsgSrv) GetRootListRemoveRows() *RootListRemoveRows {
	if x, ok := x.GetPayload().(*FormDataMsgSrv_RootListRemoveRows); ok {
		return x.RootListRemoveRows
	}
	return nil
}

func (x *FormDataMsgSrv) GetContextMenuOpen() *ContextMenuOpen {
	if x, ok := x.GetPayload().(*FormDataMsgSrv_ContextMenuOpen); ok {
		return x.ContextMenuOpen
	}
	return nil
}

func (x *FormDataMsgSrv) GetFormAction() *FormAction {
	if x, ok := x.GetPayload().(*FormDataMsgSrv_FormAction); ok {
		return x.FormAction
	}
	return nil
}

type isFormDataMsgSrv_Payload interface {
	isFormDataMsgSrv_Payload()
}

type FormDataMsgSrv_RootListOpen struct {
	RootListOpen *RootListOpen `protobuf:"bytes,2,opt,name=rootListOpen,proto3,oneof"`
}

type FormDataMsgSrv_RootListAddRows struct {
	RootListAddRows *RootListAddRows `protobuf:"bytes,3,opt,name=rootListAddRows,proto3,oneof"`
}

type FormDataMsgSrv_RootListChangeRows struct {
	RootListChangeRows *RootListChangeRows `protobuf:"bytes,4,opt,name=rootListChangeRows,proto3,oneof"`
}

type FormDataMsgSrv_RootListRemoveRows struct {
	RootListRemoveRows *RootListRemoveRows `protobuf:"bytes,5,opt,name=rootListRemoveRows,proto3,oneof"`
}

type FormDataMsgSrv_ContextMenuOpen struct {
	ContextMenuOpen *ContextMenuOpen `protobuf:"bytes,6,opt,name=contextMenuOpen,proto3,oneof"`
}

type FormDataMsgSrv_FormAction struct {
	FormAction *FormAction `protobuf:"bytes,7,opt,name=formAction,proto3,oneof"`
}

func (*FormDataMsgSrv_RootListOpen) isFormDataMsgSrv_Payload() {}

func (*FormDataMsgSrv_RootListAddRows) isFormDataMsgSrv_Payload() {}

func (*FormDataMsgSrv_RootListChangeRows) isFormDataMsgSrv_Payload() {}

func (*FormDataMsgSrv_RootListRemoveRows) isFormDataMsgSrv_Payload() {}

func (*FormDataMsgSrv_ContextMenuOpen) isFormDataMsgSrv_Payload() {}

func (*FormDataMsgSrv_FormAction) isFormDataMsgSrv_Payload() {}

var File_proto_runify_proto protoreflect.FileDescriptor

var file_proto_runify_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x4a, 0x0a, 0x08, 0x43, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x22, 0x26, 0x0a, 0x0c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x44, 0x22, 0x3c, 0x0a, 0x0a, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x28, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x44, 0x0a, 0x0e,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61,
	0x72, 0x64, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64,
	0x49, 0x44, 0x22, 0x46, 0x0a, 0x04, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x22, 0x0a, 0x0a, 0x48, 0x69,
	0x64, 0x65, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x88,
	0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x66, 0x6f, 0x72,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79,
	0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x48, 0x00, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x25, 0x0a,
	0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72,
	0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x28, 0x0a, 0x04, 0x68, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x48, 0x69, 0x64, 0x65,
	0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x48, 0x00, 0x52, 0x04, 0x68, 0x69, 0x64, 0x65, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4c, 0x0a, 0x08, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x26, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x4c, 0x6f,
	0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3b, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x46, 0x6f,
	0x72, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e,
	0x46, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x22, 0x49, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d,
	0x73, 0x67, 0x55, 0x49, 0x12, 0x2e, 0x0a, 0x08, 0x77, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x48, 0x00, 0x52, 0x08, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x4c, 0x6f, 0x67, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x56, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x73, 0x67, 0x53, 0x72, 0x76,
	0x12, 0x3a, 0x0a, 0x0c, 0x73, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e,
	0x53, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0c,
	0x73, 0x65, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4b, 0x0a, 0x13, 0x52, 0x6f, 0x6f, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x6f, 0x77, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x44, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x6f, 0x77, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72,
	0x6f, 0x77, 0x49, 0x44, 0x22, 0x89, 0x01, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x6f, 0x77, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x77, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f, 0x77, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x37, 0x0a, 0x0c, 0x52, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e,
	0x12, 0x27, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x3a, 0x0a, 0x0f, 0x52, 0x6f, 0x6f,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x27, 0x0a, 0x04,
	0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x75, 0x6e,
	0x69, 0x66, 0x79, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x77, 0x52,
	0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x3d, 0x0a, 0x12, 0x52, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x72,
	0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x75, 0x6e, 0x69,
	0x66, 0x79, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x77, 0x52, 0x04,
	0x72, 0x6f, 0x77, 0x73, 0x22, 0x45, 0x0a, 0x12, 0x52, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x2f, 0x0a, 0x04, 0x72, 0x6f,
	0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66,
	0x79, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x77, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x49, 0x44, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x28, 0x0a, 0x10, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x77, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x6f, 0x77, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x72, 0x6f, 0x77, 0x49, 0x44, 0x22, 0x0c, 0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x6d, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x64, 0x22, 0x3c, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x4d, 0x65,
	0x6e, 0x75, 0x52, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x77, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f, 0x77, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x3d, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x6e, 0x75,
	0x4f, 0x70, 0x65, 0x6e, 0x12, 0x2a, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73,
	0x22, 0x5e, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x35, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x73, 0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36,
	0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x46, 0x6f, 0x72, 0x6d,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x22, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xa2, 0x03, 0x0a, 0x0d, 0x46, 0x6f,
	0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x55, 0x49, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x6f, 0x72, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x66, 0x6f, 0x72,
	0x6d, 0x49, 0x44, 0x12, 0x3a, 0x0a, 0x0d, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x75, 0x6e,
	0x69, 0x66, 0x79, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00,
	0x52, 0x0d, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12,
	0x51, 0x0a, 0x14, 0x72, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x77, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x6f, 0x77, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x44, 0x48, 0x00, 0x52, 0x14, 0x72, 0x6f,
	0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x77, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x53, 0x0a, 0x15, 0x72, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65,
	0x6e, 0x75, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x6f, 0x77, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x44, 0x48, 0x00,
	0x52, 0x15, 0x72, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x12, 0x54, 0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x77, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66,
	0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x6f, 0x77,
	0x49, 0x44, 0x48, 0x00, 0x52, 0x17, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x6e,
	0x75, 0x52, 0x6f, 0x77, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x12, 0x34, 0x0a,
	0x0a, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xcb,
	0x03, 0x0a, 0x0e, 0x46, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x53, 0x72,
	0x76, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x12, 0x3a, 0x0a, 0x0c, 0x72, 0x6f, 0x6f,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x70, 0x65, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x43, 0x0a, 0x0f, 0x72, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x77, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x64, 0x64, 0x52, 0x6f, 0x77, 0x73, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x6f, 0x6f, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x4c, 0x0a, 0x12, 0x72, 0x6f,
	0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x6f, 0x77, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e,
	0x52, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x6f,
	0x77, 0x73, 0x48, 0x00, 0x52, 0x12, 0x72, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x4c, 0x0a, 0x12, 0x72, 0x6f, 0x6f, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x52, 0x6f,
	0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x77, 0x73,
	0x48, 0x00, 0x52, 0x12, 0x72, 0x6f, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x43, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x4d, 0x65, 0x6e, 0x75, 0x4f, 0x70, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x4d, 0x65, 0x6e, 0x75, 0x4f, 0x70, 0x65, 0x6e, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x34, 0x0a, 0x0a, 0x66,
	0x6f, 0x72, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6f, 0x72, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x37, 0x0a, 0x08,
	0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x45, 0x42, 0x55,
	0x47, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x03, 0x2a, 0x23, 0x0a, 0x0d, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x48, 0x4f, 0x57, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x48, 0x49, 0x44, 0x45, 0x10, 0x01, 0x2a, 0x1d, 0x0a, 0x0b, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x2a, 0x40, 0x0a, 0x0e, 0x46, 0x6f, 0x72,
	0x6d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x43,
	0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4c,
	0x4f, 0x53, 0x45, 0x5f, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x48, 0x4f,
	0x57, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x02, 0x32, 0xe5, 0x02, 0x0a, 0x06,
	0x52, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x12, 0x43, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x14, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66,
	0x79, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x73, 0x67, 0x55, 0x49, 0x1a, 0x15,
	0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d,
	0x73, 0x67, 0x53, 0x72, 0x76, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x46, 0x0a, 0x0f, 0x46,
	0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x15,
	0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x4d, 0x73, 0x67, 0x55, 0x49, 0x1a, 0x16, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x46,
	0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x53, 0x72, 0x76, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x12, 0x28, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x0d,
	0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e,
	0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x22, 0x00, 0x12, 0x35, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x2e, 0x72, 0x75,
	0x6e, 0x69, 0x66, 0x79, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x43, 0x61, 0x72,
	0x64, 0x1a, 0x0f, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x43, 0x61, 0x72, 0x64, 0x1a, 0x0e, 0x2e, 0x72,
	0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x33,
	0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x72, 0x75, 0x6e, 0x69,
	0x66, 0x79, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x0e, 0x2e, 0x72, 0x75, 0x6e, 0x69, 0x66, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_runify_proto_rawDescOnce sync.Once
	file_proto_runify_proto_rawDescData = file_proto_runify_proto_rawDesc
)

func file_proto_runify_proto_rawDescGZIP() []byte {
	file_proto_runify_proto_rawDescOnce.Do(func() {
		file_proto_runify_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_runify_proto_rawDescData)
	})
	return file_proto_runify_proto_rawDescData
}

var file_proto_runify_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_runify_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_runify_proto_goTypes = []interface{}{
	(LogLevel)(0),               // 0: runify.LogLevel
	(FormStateType)(0),          // 1: runify.FormStateType
	(MessageType)(0),            // 2: runify.MessageType
	(FormActionType)(0),         // 3: runify.FormActionType
	(*Empty)(nil),               // 4: runify.Empty
	(*CardItem)(nil),            // 5: runify.CardItem
	(*SelectedCard)(nil),        // 6: runify.SelectedCard
	(*ActionItem)(nil),          // 7: runify.ActionItem
	(*Actions)(nil),             // 8: runify.Actions
	(*SelectedAction)(nil),      // 9: runify.SelectedAction
	(*Form)(nil),                // 10: runify.Form
	(*HideWindow)(nil),          // 11: runify.HideWindow
	(*Result)(nil),              // 12: runify.Result
	(*WriteLog)(nil),            // 13: runify.WriteLog
	(*SetFormState)(nil),        // 14: runify.SetFormState
	(*ServiceMsgUI)(nil),        // 15: runify.ServiceMsgUI
	(*ServiceMsgSrv)(nil),       // 16: runify.ServiceMsgSrv
	(*RootListRowGlobalID)(nil), // 17: runify.RootListRowGlobalID
	(*RootListRow)(nil),         // 18: runify.RootListRow
	(*RootListOpen)(nil),        // 19: runify.RootListOpen
	(*RootListAddRows)(nil),     // 20: runify.RootListAddRows
	(*RootListChangeRows)(nil),  // 21: runify.RootListChangeRows
	(*RootListRemoveRows)(nil),  // 22: runify.RootListRemoveRows
	(*ContextMenuRowID)(nil),    // 23: runify.ContextMenuRowID
	(*FormClosed)(nil),          // 24: runify.FormClosed
	(*ContextMenuRow)(nil),      // 25: runify.ContextMenuRow
	(*ContextMenuOpen)(nil),     // 26: runify.ContextMenuOpen
	(*UserMessage)(nil),         // 27: runify.UserMessage
	(*FormAction)(nil),          // 28: runify.FormAction
	(*FilterData)(nil),          // 29: runify.FilterData
	(*FormDataMsgUI)(nil),       // 30: runify.FormDataMsgUI
	(*FormDataMsgSrv)(nil),      // 31: runify.FormDataMsgSrv
}
var file_proto_runify_proto_depIdxs = []int32{
	7,  // 0: runify.Actions.items:type_name -> runify.ActionItem
	5,  // 1: runify.Form.cards:type_name -> runify.CardItem
	10, // 2: runify.Result.form:type_name -> runify.Form
	4,  // 3: runify.Result.empty:type_name -> runify.Empty
	11, // 4: runify.Result.hide:type_name -> runify.HideWindow
	0,  // 5: runify.WriteLog.level:type_name -> runify.LogLevel
	1,  // 6: runify.SetFormState.state:type_name -> runify.FormStateType
	13, // 7: runify.ServiceMsgUI.writeLog:type_name -> runify.WriteLog
	14, // 8: runify.ServiceMsgSrv.setFormState:type_name -> runify.SetFormState
	18, // 9: runify.RootListOpen.rows:type_name -> runify.RootListRow
	18, // 10: runify.RootListAddRows.rows:type_name -> runify.RootListRow
	18, // 11: runify.RootListChangeRows.rows:type_name -> runify.RootListRow
	17, // 12: runify.RootListRemoveRows.rows:type_name -> runify.RootListRowGlobalID
	25, // 13: runify.ContextMenuOpen.rows:type_name -> runify.ContextMenuRow
	2,  // 14: runify.UserMessage.messageType:type_name -> runify.MessageType
	3,  // 15: runify.FormAction.actionType:type_name -> runify.FormActionType
	27, // 16: runify.FormAction.message:type_name -> runify.UserMessage
	29, // 17: runify.FormDataMsgUI.filterChanged:type_name -> runify.FilterData
	17, // 18: runify.FormDataMsgUI.rootListRowActivated:type_name -> runify.RootListRowGlobalID
	17, // 19: runify.FormDataMsgUI.rootListMenuActivated:type_name -> runify.RootListRowGlobalID
	23, // 20: runify.FormDataMsgUI.contextMenuRowActivated:type_name -> runify.ContextMenuRowID
	24, // 21: runify.FormDataMsgUI.formClosed:type_name -> runify.FormClosed
	19, // 22: runify.FormDataMsgSrv.rootListOpen:type_name -> runify.RootListOpen
	20, // 23: runify.FormDataMsgSrv.rootListAddRows:type_name -> runify.RootListAddRows
	21, // 24: runify.FormDataMsgSrv.rootListChangeRows:type_name -> runify.RootListChangeRows
	22, // 25: runify.FormDataMsgSrv.rootListRemoveRows:type_name -> runify.RootListRemoveRows
	26, // 26: runify.FormDataMsgSrv.contextMenuOpen:type_name -> runify.ContextMenuOpen
	28, // 27: runify.FormDataMsgSrv.formAction:type_name -> runify.FormAction
	15, // 28: runify.Runify.ServiceChannel:input_type -> runify.ServiceMsgUI
	30, // 29: runify.Runify.FormDataChannel:input_type -> runify.FormDataMsgUI
	4,  // 30: runify.Runify.GetRoot:input_type -> runify.Empty
	6,  // 31: runify.Runify.GetActions:input_type -> runify.SelectedCard
	6,  // 32: runify.Runify.ExecuteDefault:input_type -> runify.SelectedCard
	9,  // 33: runify.Runify.Execute:input_type -> runify.SelectedAction
	16, // 34: runify.Runify.ServiceChannel:output_type -> runify.ServiceMsgSrv
	31, // 35: runify.Runify.FormDataChannel:output_type -> runify.FormDataMsgSrv
	10, // 36: runify.Runify.GetRoot:output_type -> runify.Form
	8,  // 37: runify.Runify.GetActions:output_type -> runify.Actions
	12, // 38: runify.Runify.ExecuteDefault:output_type -> runify.Result
	12, // 39: runify.Runify.Execute:output_type -> runify.Result
	34, // [34:40] is the sub-list for method output_type
	28, // [28:34] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_runify_proto_init() }
func file_proto_runify_proto_init() {
	if File_proto_runify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_runify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectedCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Actions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectedAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Form); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HideWindow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetFormState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceMsgUI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceMsgSrv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootListRowGlobalID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootListRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootListOpen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootListAddRows); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootListChangeRows); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootListRemoveRows); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContextMenuRowID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormClosed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContextMenuRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContextMenuOpen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormDataMsgUI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_runify_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormDataMsgSrv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_runify_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*Result_Form)(nil),
		(*Result_Empty)(nil),
		(*Result_Hide)(nil),
	}
	file_proto_runify_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*ServiceMsgUI_WriteLog)(nil),
	}
	file_proto_runify_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*ServiceMsgSrv_SetFormState)(nil),
	}
	file_proto_runify_proto_msgTypes[26].OneofWrappers = []interface{}{
		(*FormDataMsgUI_FilterChanged)(nil),
		(*FormDataMsgUI_RootListRowActivated)(nil),
		(*FormDataMsgUI_RootListMenuActivated)(nil),
		(*FormDataMsgUI_ContextMenuRowActivated)(nil),
		(*FormDataMsgUI_FormClosed)(nil),
	}
	file_proto_runify_proto_msgTypes[27].OneofWrappers = []interface{}{
		(*FormDataMsgSrv_RootListOpen)(nil),
		(*FormDataMsgSrv_RootListAddRows)(nil),
		(*FormDataMsgSrv_RootListChangeRows)(nil),
		(*FormDataMsgSrv_RootListRemoveRows)(nil),
		(*FormDataMsgSrv_ContextMenuOpen)(nil),
		(*FormDataMsgSrv_FormAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_runify_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_runify_proto_goTypes,
		DependencyIndexes: file_proto_runify_proto_depIdxs,
		EnumInfos:         file_proto_runify_proto_enumTypes,
		MessageInfos:      file_proto_runify_proto_msgTypes,
	}.Build()
	File_proto_runify_proto = out.File
	file_proto_runify_proto_rawDesc = nil
	file_proto_runify_proto_goTypes = nil
	file_proto_runify_proto_depIdxs = nil
}
