package shortcut

import "go.uber.org/zap"

type ModId uint8

func (id ModId) ZapField() zap.Field {
	return zap.Uint8("ModId", uint8(id))
}

func (id ModId) ZapFieldPrefix(prefix string) zap.Field {
	return zap.Uint8(prefix+"ModId", uint8(id))
}

type KeyId uint16

func (id KeyId) ZapField() zap.Field {
	return zap.Uint16("KeyId", uint16(id))
}

func (id KeyId) ZapFieldPrefix(prefix string) zap.Field {
	return zap.Uint16(prefix+"KeyId", uint16(id))
}

type HotkeyId uint32

func (id HotkeyId) ZapField() zap.Field {
	return zap.Uint32("HotkeyId", uint32(id))
}

func (id HotkeyId) ZapFieldPrefix(prefix string) zap.Field {
	return zap.Uint32(prefix+"HotkeyId", uint32(id))
}

const (
	ModShift ModId = 1 << iota
	ModControl
	ModAlt
	ModSuper
)

const (
	ID_VoidSymbol KeyId = iota
	ID_BackSpace
	ID_Tab
	ID_Linefeed
	ID_Clear
	ID_Return
	ID_Pause
	ID_Scroll_Lock
	ID_Sys_Req
	ID_Escape
	ID_Delete
	ID_Multi_key
	ID_Codeinput
	ID_SingleCandidate
	ID_MultipleCandidate
	ID_PreviousCandidate
	ID_Kanji
	ID_Muhenkan
	ID_Henkan_Mode
	ID_Henkan
	ID_Romaji
	ID_Hiragana
	ID_Katakana
	ID_Hiragana_Katakana
	ID_Zenkaku
	ID_Hankaku
	ID_Zenkaku_Hankaku
	ID_Touroku
	ID_Massyo
	ID_Kana_Lock
	ID_Kana_Shift
	ID_Eisu_Shift
	ID_Eisu_toggle
	ID_Kanji_Bangou
	ID_Zen_Koho
	ID_Mae_Koho
	ID_Home
	ID_Left
	ID_Up
	ID_Right
	ID_Down
	ID_Prior
	ID_Page_Up
	ID_Next
	ID_Page_Down
	ID_End
	ID_Begin
	ID_Select
	ID_Print
	ID_Execute
	ID_Insert
	ID_Undo
	ID_Redo
	ID_Menu
	ID_Find
	ID_Cancel
	ID_Help
	ID_Break
	ID_Mode_switch
	ID_script_switch
	ID_Num_Lock
	ID_KP_Space
	ID_KP_Tab
	ID_KP_Enter
	ID_KP_F1
	ID_KP_F2
	ID_KP_F3
	ID_KP_F4
	ID_KP_Home
	ID_KP_Left
	ID_KP_Up
	ID_KP_Right
	ID_KP_Down
	ID_KP_Prior
	ID_KP_Page_Up
	ID_KP_Next
	ID_KP_Page_Down
	ID_KP_End
	ID_KP_Begin
	ID_KP_Insert
	ID_KP_Delete
	ID_KP_Equal
	ID_KP_Multiply
	ID_KP_Add
	ID_KP_Separator
	ID_KP_Subtract
	ID_KP_Decimal
	ID_KP_Divide
	ID_KP_0
	ID_KP_1
	ID_KP_2
	ID_KP_3
	ID_KP_4
	ID_KP_5
	ID_KP_6
	ID_KP_7
	ID_KP_8
	ID_KP_9
	ID_F1
	ID_F2
	ID_F3
	ID_F4
	ID_F5
	ID_F6
	ID_F7
	ID_F8
	ID_F9
	ID_F10
	ID_F11
	ID_L1
	ID_F12
	ID_L2
	ID_F13
	ID_L3
	ID_F14
	ID_L4
	ID_F15
	ID_L5
	ID_F16
	ID_L6
	ID_F17
	ID_L7
	ID_F18
	ID_L8
	ID_F19
	ID_L9
	ID_F20
	ID_L10
	ID_F21
	ID_R1
	ID_F22
	ID_R2
	ID_F23
	ID_R3
	ID_F24
	ID_R4
	ID_F25
	ID_R5
	ID_F26
	ID_R6
	ID_F27
	ID_R7
	ID_F28
	ID_R8
	ID_F29
	ID_R9
	ID_F30
	ID_R10
	ID_F31
	ID_R11
	ID_F32
	ID_R12
	ID_F33
	ID_R13
	ID_F34
	ID_R14
	ID_F35
	ID_R15
	ID_Shift_L
	ID_Shift_R
	ID_Control_L
	ID_Control_R
	ID_Caps_Lock
	ID_Shift_Lock
	ID_Meta_L
	ID_Meta_R
	ID_Alt_L
	ID_Alt_R
	ID_Super_L
	ID_Super_R
	ID_Hyper_L
	ID_Hyper_R
	ID_ISO_Lock
	ID_ISO_Level2_Latch
	ID_ISO_Level3_Shift
	ID_ISO_Level3_Latch
	ID_ISO_Level3_Lock
	ID_ISO_Level5_Shift
	ID_ISO_Level5_Latch
	ID_ISO_Level5_Lock
	ID_ISO_Group_Shift
	ID_ISO_Group_Latch
	ID_ISO_Group_Lock
	ID_ISO_Next_Group
	ID_ISO_Next_Group_Lock
	ID_ISO_Prev_Group
	ID_ISO_Prev_Group_Lock
	ID_ISO_First_Group
	ID_ISO_First_Group_Lock
	ID_ISO_Last_Group
	ID_ISO_Last_Group_Lock
	ID_ISO_Left_Tab
	ID_ISO_Move_Line_Up
	ID_ISO_Move_Line_Down
	ID_ISO_Partial_Line_Up
	ID_ISO_Partial_Line_Down
	ID_ISO_Partial_Space_Left
	ID_ISO_Partial_Space_Right
	ID_ISO_Set_Margin_Left
	ID_ISO_Set_Margin_Right
	ID_ISO_Release_Margin_Left
	ID_ISO_Release_Margin_Right
	ID_ISO_Release_Both_Margins
	ID_ISO_Fast_Cursor_Left
	ID_ISO_Fast_Cursor_Right
	ID_ISO_Fast_Cursor_Up
	ID_ISO_Fast_Cursor_Down
	ID_ISO_Continuous_Underline
	ID_ISO_Discontinuous_Underline
	ID_ISO_Emphasize
	ID_ISO_Center_Object
	ID_ISO_Enter
	ID_dead_grave
	ID_dead_acute
	ID_dead_circumflex
	ID_dead_tilde
	ID_dead_perispomeni
	ID_dead_macron
	ID_dead_breve
	ID_dead_abovedot
	ID_dead_diaeresis
	ID_dead_abovering
	ID_dead_doubleacute
	ID_dead_caron
	ID_dead_cedilla
	ID_dead_ogonek
	ID_dead_iota
	ID_dead_voiced_sound
	ID_dead_semivoiced_sound
	ID_dead_belowdot
	ID_dead_hook
	ID_dead_horn
	ID_dead_stroke
	ID_dead_abovecomma
	ID_dead_psili
	ID_dead_abovereversedcomma
	ID_dead_dasia
	ID_dead_doublegrave
	ID_dead_belowring
	ID_dead_belowmacron
	ID_dead_belowcircumflex
	ID_dead_belowtilde
	ID_dead_belowbreve
	ID_dead_belowdiaeresis
	ID_dead_invertedbreve
	ID_dead_belowcomma
	ID_dead_currency
	ID_dead_a
	ID_dead_A
	ID_dead_e
	ID_dead_E
	ID_dead_i
	ID_dead_I
	ID_dead_o
	ID_dead_O
	ID_dead_u
	ID_dead_U
	ID_dead_small_schwa
	ID_dead_capital_schwa
	ID_First_Virtual_Screen
	ID_Prev_Virtual_Screen
	ID_Next_Virtual_Screen
	ID_Last_Virtual_Screen
	ID_Terminate_Server
	ID_AccessX_Enable
	ID_AccessX_Feedback_Enable
	ID_RepeatKeys_Enable
	ID_SlowKeys_Enable
	ID_BounceKeys_Enable
	ID_StickyKeys_Enable
	ID_MouseKeys_Enable
	ID_MouseKeys_Accel_Enable
	ID_Overlay1_Enable
	ID_Overlay2_Enable
	ID_AudibleBell_Enable
	ID_Pointer_Left
	ID_Pointer_Right
	ID_Pointer_Up
	ID_Pointer_Down
	ID_Pointer_UpLeft
	ID_Pointer_UpRight
	ID_Pointer_DownLeft
	ID_Pointer_DownRight
	ID_Pointer_Button_Dflt
	ID_Pointer_Button1
	ID_Pointer_Button2
	ID_Pointer_Button3
	ID_Pointer_Button4
	ID_Pointer_Button5
	ID_Pointer_DblClick_Dflt
	ID_Pointer_DblClick1
	ID_Pointer_DblClick2
	ID_Pointer_DblClick3
	ID_Pointer_DblClick4
	ID_Pointer_DblClick5
	ID_Pointer_Drag_Dflt
	ID_Pointer_Drag1
	ID_Pointer_Drag2
	ID_Pointer_Drag3
	ID_Pointer_Drag4
	ID_Pointer_Drag5
	ID_Pointer_EnableKeys
	ID_Pointer_Accelerate
	ID_Pointer_DfltBtnNext
	ID_Pointer_DfltBtnPrev
	ID_3270_Duplicate
	ID_3270_FieldMark
	ID_3270_Right2
	ID_3270_Left2
	ID_3270_BackTab
	ID_3270_EraseEOF
	ID_3270_EraseInput
	ID_3270_Reset
	ID_3270_Quit
	ID_3270_PA1
	ID_3270_PA2
	ID_3270_PA3
	ID_3270_Test
	ID_3270_Attn
	ID_3270_CursorBlink
	ID_3270_AltCursor
	ID_3270_KeyClick
	ID_3270_Jump
	ID_3270_Ident
	ID_3270_Rule
	ID_3270_Copy
	ID_3270_Play
	ID_3270_Setup
	ID_3270_Record
	ID_3270_ChangeScreen
	ID_3270_DeleteWord
	ID_3270_ExSelect
	ID_3270_CursorSelect
	ID_3270_PrintScreen
	ID_3270_Enter
	ID_space
	ID_exclam
	ID_quotedbl
	ID_numbersign
	ID_dollar
	ID_percent
	ID_ampersand
	ID_apostrophe
	ID_quoteright
	ID_parenleft
	ID_parenright
	ID_asterisk
	ID_plus
	ID_comma
	ID_minus
	ID_period
	ID_slash
	ID_0
	ID_1
	ID_2
	ID_3
	ID_4
	ID_5
	ID_6
	ID_7
	ID_8
	ID_9
	ID_colon
	ID_semicolon
	ID_less
	ID_equal
	ID_greater
	ID_question
	ID_at
	ID_A
	ID_B
	ID_C
	ID_D
	ID_E
	ID_F
	ID_G
	ID_H
	ID_I
	ID_J
	ID_K
	ID_L
	ID_M
	ID_N
	ID_O
	ID_P
	ID_Q
	ID_R
	ID_S
	ID_T
	ID_U
	ID_V
	ID_W
	ID_X
	ID_Y
	ID_Z
	ID_bracketleft
	ID_backslash
	ID_bracketright
	ID_asciicircum
	ID_underscore
	ID_grave
	ID_quoteleft
	ID_a
	ID_b
	ID_c
	ID_d
	ID_e
	ID_f
	ID_g
	ID_h
	ID_i
	ID_j
	ID_k
	ID_l
	ID_m
	ID_n
	ID_o
	ID_p
	ID_q
	ID_r
	ID_s
	ID_t
	ID_u
	ID_v
	ID_w
	ID_x
	ID_y
	ID_z
	ID_braceleft
	ID_bar
	ID_braceright
	ID_asciitilde
	ID_nobreakspace
	ID_exclamdown
	ID_cent
	ID_sterling
	ID_currency
	ID_yen
	ID_brokenbar
	ID_section
	ID_diaeresis
	ID_copyright
	ID_ordfeminine
	ID_guillemotleft
	ID_notsign
	ID_hyphen
	ID_registered
	ID_macron
	ID_degree
	ID_plusminus
	ID_twosuperior
	ID_threesuperior
	ID_acute
	ID_mu
	ID_paragraph
	ID_periodcentered
	ID_cedilla
	ID_onesuperior
	ID_masculine
	ID_guillemotright
	ID_onequarter
	ID_onehalf
	ID_threequarters
	ID_questiondown
	ID_Agrave
	ID_Aacute
	ID_Acircumflex
	ID_Atilde
	ID_Adiaeresis
	ID_Aring
	ID_AE
	ID_Ccedilla
	ID_Egrave
	ID_Eacute
	ID_Ecircumflex
	ID_Ediaeresis
	ID_Igrave
	ID_Iacute
	ID_Icircumflex
	ID_Idiaeresis
	ID_ETH
	ID_Eth
	ID_Ntilde
	ID_Ograve
	ID_Oacute
	ID_Ocircumflex
	ID_Otilde
	ID_Odiaeresis
	ID_multiply
	ID_Oslash
	ID_Ooblique
	ID_Ugrave
	ID_Uacute
	ID_Ucircumflex
	ID_Udiaeresis
	ID_Yacute
	ID_THORN
	ID_Thorn
	ID_ssharp
	ID_agrave
	ID_aacute
	ID_acircumflex
	ID_atilde
	ID_adiaeresis
	ID_aring
	ID_ae
	ID_ccedilla
	ID_egrave
	ID_eacute
	ID_ecircumflex
	ID_ediaeresis
	ID_igrave
	ID_iacute
	ID_icircumflex
	ID_idiaeresis
	ID_eth
	ID_ntilde
	ID_ograve
	ID_oacute
	ID_ocircumflex
	ID_otilde
	ID_odiaeresis
	ID_division
	ID_oslash
	ID_ooblique
	ID_ugrave
	ID_uacute
	ID_ucircumflex
	ID_udiaeresis
	ID_yacute
	ID_thorn
	ID_ydiaeresis
	ID_Aogonek
	ID_breve
	ID_Lstroke
	ID_Lcaron
	ID_Sacute
	ID_Scaron
	ID_Scedilla
	ID_Tcaron
	ID_Zacute
	ID_Zcaron
	ID_Zabovedot
	ID_aogonek
	ID_ogonek
	ID_lstroke
	ID_lcaron
	ID_sacute
	ID_caron
	ID_scaron
	ID_scedilla
	ID_tcaron
	ID_zacute
	ID_doubleacute
	ID_zcaron
	ID_zabovedot
	ID_Racute
	ID_Abreve
	ID_Lacute
	ID_Cacute
	ID_Ccaron
	ID_Eogonek
	ID_Ecaron
	ID_Dcaron
	ID_Dstroke
	ID_Nacute
	ID_Ncaron
	ID_Odoubleacute
	ID_Rcaron
	ID_Uring
	ID_Udoubleacute
	ID_Tcedilla
	ID_racute
	ID_abreve
	ID_lacute
	ID_cacute
	ID_ccaron
	ID_eogonek
	ID_ecaron
	ID_dcaron
	ID_dstroke
	ID_nacute
	ID_ncaron
	ID_odoubleacute
	ID_udoubleacute
	ID_rcaron
	ID_uring
	ID_tcedilla
	ID_abovedot
	ID_Hstroke
	ID_Hcircumflex
	ID_Iabovedot
	ID_Gbreve
	ID_Jcircumflex
	ID_hstroke
	ID_hcircumflex
	ID_idotless
	ID_gbreve
	ID_jcircumflex
	ID_Cabovedot
	ID_Ccircumflex
	ID_Gabovedot
	ID_Gcircumflex
	ID_Ubreve
	ID_Scircumflex
	ID_cabovedot
	ID_ccircumflex
	ID_gabovedot
	ID_gcircumflex
	ID_ubreve
	ID_scircumflex
	ID_kra
	ID_kappa
	ID_Rcedilla
	ID_Itilde
	ID_Lcedilla
	ID_Emacron
	ID_Gcedilla
	ID_Tslash
	ID_rcedilla
	ID_itilde
	ID_lcedilla
	ID_emacron
	ID_gcedilla
	ID_tslash
	ID_ENG
	ID_eng
	ID_Amacron
	ID_Iogonek
	ID_Eabovedot
	ID_Imacron
	ID_Ncedilla
	ID_Omacron
	ID_Kcedilla
	ID_Uogonek
	ID_Utilde
	ID_Umacron
	ID_amacron
	ID_iogonek
	ID_eabovedot
	ID_imacron
	ID_ncedilla
	ID_omacron
	ID_kcedilla
	ID_uogonek
	ID_utilde
	ID_umacron
	ID_Babovedot
	ID_babovedot
	ID_Dabovedot
	ID_Wgrave
	ID_Wacute
	ID_dabovedot
	ID_Ygrave
	ID_Fabovedot
	ID_fabovedot
	ID_Mabovedot
	ID_mabovedot
	ID_Pabovedot
	ID_wgrave
	ID_pabovedot
	ID_wacute
	ID_Sabovedot
	ID_ygrave
	ID_Wdiaeresis
	ID_wdiaeresis
	ID_sabovedot
	ID_Wcircumflex
	ID_Tabovedot
	ID_Ycircumflex
	ID_wcircumflex
	ID_tabovedot
	ID_ycircumflex
	ID_OE
	ID_oe
	ID_Ydiaeresis
	ID_overline
	ID_kana_fullstop
	ID_kana_openingbracket
	ID_kana_closingbracket
	ID_kana_comma
	ID_kana_conjunctive
	ID_kana_middledot
	ID_kana_WO
	ID_kana_a
	ID_kana_i
	ID_kana_u
	ID_kana_e
	ID_kana_o
	ID_kana_ya
	ID_kana_yu
	ID_kana_yo
	ID_kana_tsu
	ID_kana_tu
	ID_prolongedsound
	ID_kana_A
	ID_kana_I
	ID_kana_U
	ID_kana_E
	ID_kana_O
	ID_kana_KA
	ID_kana_KI
	ID_kana_KU
	ID_kana_KE
	ID_kana_KO
	ID_kana_SA
	ID_kana_SHI
	ID_kana_SU
	ID_kana_SE
	ID_kana_SO
	ID_kana_TA
	ID_kana_CHI
	ID_kana_TI
	ID_kana_TSU
	ID_kana_TU
	ID_kana_TE
	ID_kana_TO
	ID_kana_NA
	ID_kana_NI
	ID_kana_NU
	ID_kana_NE
	ID_kana_NO
	ID_kana_HA
	ID_kana_HI
	ID_kana_FU
	ID_kana_HU
	ID_kana_HE
	ID_kana_HO
	ID_kana_MA
	ID_kana_MI
	ID_kana_MU
	ID_kana_ME
	ID_kana_MO
	ID_kana_YA
	ID_kana_YU
	ID_kana_YO
	ID_kana_RA
	ID_kana_RI
	ID_kana_RU
	ID_kana_RE
	ID_kana_RO
	ID_kana_WA
	ID_kana_N
	ID_voicedsound
	ID_semivoicedsound
	ID_kana_switch
	ID_Farsi_0
	ID_Farsi_1
	ID_Farsi_2
	ID_Farsi_3
	ID_Farsi_4
	ID_Farsi_5
	ID_Farsi_6
	ID_Farsi_7
	ID_Farsi_8
	ID_Farsi_9
	ID_Arabic_percent
	ID_Arabic_superscript_alef
	ID_Arabic_tteh
	ID_Arabic_peh
	ID_Arabic_tcheh
	ID_Arabic_ddal
	ID_Arabic_rreh
	ID_Arabic_comma
	ID_Arabic_fullstop
	ID_Arabic_0
	ID_Arabic_1
	ID_Arabic_2
	ID_Arabic_3
	ID_Arabic_4
	ID_Arabic_5
	ID_Arabic_6
	ID_Arabic_7
	ID_Arabic_8
	ID_Arabic_9
	ID_Arabic_semicolon
	ID_Arabic_question_mark
	ID_Arabic_hamza
	ID_Arabic_maddaonalef
	ID_Arabic_hamzaonalef
	ID_Arabic_hamzaonwaw
	ID_Arabic_hamzaunderalef
	ID_Arabic_hamzaonyeh
	ID_Arabic_alef
	ID_Arabic_beh
	ID_Arabic_tehmarbuta
	ID_Arabic_teh
	ID_Arabic_theh
	ID_Arabic_jeem
	ID_Arabic_hah
	ID_Arabic_khah
	ID_Arabic_dal
	ID_Arabic_thal
	ID_Arabic_ra
	ID_Arabic_zain
	ID_Arabic_seen
	ID_Arabic_sheen
	ID_Arabic_sad
	ID_Arabic_dad
	ID_Arabic_tah
	ID_Arabic_zah
	ID_Arabic_ain
	ID_Arabic_ghain
	ID_Arabic_tatweel
	ID_Arabic_feh
	ID_Arabic_qaf
	ID_Arabic_kaf
	ID_Arabic_lam
	ID_Arabic_meem
	ID_Arabic_noon
	ID_Arabic_ha
	ID_Arabic_heh
	ID_Arabic_waw
	ID_Arabic_alefmaksura
	ID_Arabic_yeh
	ID_Arabic_fathatan
	ID_Arabic_dammatan
	ID_Arabic_kasratan
	ID_Arabic_fatha
	ID_Arabic_damma
	ID_Arabic_kasra
	ID_Arabic_shadda
	ID_Arabic_sukun
	ID_Arabic_madda_above
	ID_Arabic_hamza_above
	ID_Arabic_hamza_below
	ID_Arabic_jeh
	ID_Arabic_veh
	ID_Arabic_keheh
	ID_Arabic_gaf
	ID_Arabic_noon_ghunna
	ID_Arabic_heh_doachashmee
	ID_Farsi_yeh
	ID_Arabic_farsi_yeh
	ID_Arabic_yeh_baree
	ID_Arabic_heh_goal
	ID_Arabic_switch
	ID_Cyrillic_GHE_bar
	ID_Cyrillic_ghe_bar
	ID_Cyrillic_ZHE_descender
	ID_Cyrillic_zhe_descender
	ID_Cyrillic_KA_descender
	ID_Cyrillic_ka_descender
	ID_Cyrillic_KA_vertstroke
	ID_Cyrillic_ka_vertstroke
	ID_Cyrillic_EN_descender
	ID_Cyrillic_en_descender
	ID_Cyrillic_U_straight
	ID_Cyrillic_u_straight
	ID_Cyrillic_U_straight_bar
	ID_Cyrillic_u_straight_bar
	ID_Cyrillic_HA_descender
	ID_Cyrillic_ha_descender
	ID_Cyrillic_CHE_descender
	ID_Cyrillic_che_descender
	ID_Cyrillic_CHE_vertstroke
	ID_Cyrillic_che_vertstroke
	ID_Cyrillic_SHHA
	ID_Cyrillic_shha
	ID_Cyrillic_SCHWA
	ID_Cyrillic_schwa
	ID_Cyrillic_I_macron
	ID_Cyrillic_i_macron
	ID_Cyrillic_O_bar
	ID_Cyrillic_o_bar
	ID_Cyrillic_U_macron
	ID_Cyrillic_u_macron
	ID_Serbian_dje
	ID_Macedonia_gje
	ID_Cyrillic_io
	ID_Ukrainian_ie
	ID_Ukranian_je
	ID_Macedonia_dse
	ID_Ukrainian_i
	ID_Ukranian_i
	ID_Ukrainian_yi
	ID_Ukranian_yi
	ID_Cyrillic_je
	ID_Serbian_je
	ID_Cyrillic_lje
	ID_Serbian_lje
	ID_Cyrillic_nje
	ID_Serbian_nje
	ID_Serbian_tshe
	ID_Macedonia_kje
	ID_Ukrainian_ghe_with_upturn
	ID_Byelorussian_shortu
	ID_Cyrillic_dzhe
	ID_Serbian_dze
	ID_numerosign
	ID_Serbian_DJE
	ID_Macedonia_GJE
	ID_Cyrillic_IO
	ID_Ukrainian_IE
	ID_Ukranian_JE
	ID_Macedonia_DSE
	ID_Ukrainian_I
	ID_Ukranian_I
	ID_Ukrainian_YI
	ID_Ukranian_YI
	ID_Cyrillic_JE
	ID_Serbian_JE
	ID_Cyrillic_LJE
	ID_Serbian_LJE
	ID_Cyrillic_NJE
	ID_Serbian_NJE
	ID_Serbian_TSHE
	ID_Macedonia_KJE
	ID_Ukrainian_GHE_WITH_UPTURN
	ID_Byelorussian_SHORTU
	ID_Cyrillic_DZHE
	ID_Serbian_DZE
	ID_Cyrillic_yu
	ID_Cyrillic_a
	ID_Cyrillic_be
	ID_Cyrillic_tse
	ID_Cyrillic_de
	ID_Cyrillic_ie
	ID_Cyrillic_ef
	ID_Cyrillic_ghe
	ID_Cyrillic_ha
	ID_Cyrillic_i
	ID_Cyrillic_shorti
	ID_Cyrillic_ka
	ID_Cyrillic_el
	ID_Cyrillic_em
	ID_Cyrillic_en
	ID_Cyrillic_o
	ID_Cyrillic_pe
	ID_Cyrillic_ya
	ID_Cyrillic_er
	ID_Cyrillic_es
	ID_Cyrillic_te
	ID_Cyrillic_u
	ID_Cyrillic_zhe
	ID_Cyrillic_ve
	ID_Cyrillic_softsign
	ID_Cyrillic_yeru
	ID_Cyrillic_ze
	ID_Cyrillic_sha
	ID_Cyrillic_e
	ID_Cyrillic_shcha
	ID_Cyrillic_che
	ID_Cyrillic_hardsign
	ID_Cyrillic_YU
	ID_Cyrillic_A
	ID_Cyrillic_BE
	ID_Cyrillic_TSE
	ID_Cyrillic_DE
	ID_Cyrillic_IE
	ID_Cyrillic_EF
	ID_Cyrillic_GHE
	ID_Cyrillic_HA
	ID_Cyrillic_I
	ID_Cyrillic_SHORTI
	ID_Cyrillic_KA
	ID_Cyrillic_EL
	ID_Cyrillic_EM
	ID_Cyrillic_EN
	ID_Cyrillic_O
	ID_Cyrillic_PE
	ID_Cyrillic_YA
	ID_Cyrillic_ER
	ID_Cyrillic_ES
	ID_Cyrillic_TE
	ID_Cyrillic_U
	ID_Cyrillic_ZHE
	ID_Cyrillic_VE
	ID_Cyrillic_SOFTSIGN
	ID_Cyrillic_YERU
	ID_Cyrillic_ZE
	ID_Cyrillic_SHA
	ID_Cyrillic_E
	ID_Cyrillic_SHCHA
	ID_Cyrillic_CHE
	ID_Cyrillic_HARDSIGN
	ID_Greek_ALPHAaccent
	ID_Greek_EPSILONaccent
	ID_Greek_ETAaccent
	ID_Greek_IOTAaccent
	ID_Greek_IOTAdieresis
	ID_Greek_IOTAdiaeresis
	ID_Greek_OMICRONaccent
	ID_Greek_UPSILONaccent
	ID_Greek_UPSILONdieresis
	ID_Greek_OMEGAaccent
	ID_Greek_accentdieresis
	ID_Greek_horizbar
	ID_Greek_alphaaccent
	ID_Greek_epsilonaccent
	ID_Greek_etaaccent
	ID_Greek_iotaaccent
	ID_Greek_iotadieresis
	ID_Greek_iotaaccentdieresis
	ID_Greek_omicronaccent
	ID_Greek_upsilonaccent
	ID_Greek_upsilondieresis
	ID_Greek_upsilonaccentdieresis
	ID_Greek_omegaaccent
	ID_Greek_ALPHA
	ID_Greek_BETA
	ID_Greek_GAMMA
	ID_Greek_DELTA
	ID_Greek_EPSILON
	ID_Greek_ZETA
	ID_Greek_ETA
	ID_Greek_THETA
	ID_Greek_IOTA
	ID_Greek_KAPPA
	ID_Greek_LAMDA
	ID_Greek_LAMBDA
	ID_Greek_MU
	ID_Greek_NU
	ID_Greek_XI
	ID_Greek_OMICRON
	ID_Greek_PI
	ID_Greek_RHO
	ID_Greek_SIGMA
	ID_Greek_TAU
	ID_Greek_UPSILON
	ID_Greek_PHI
	ID_Greek_CHI
	ID_Greek_PSI
	ID_Greek_OMEGA
	ID_Greek_alpha
	ID_Greek_beta
	ID_Greek_gamma
	ID_Greek_delta
	ID_Greek_epsilon
	ID_Greek_zeta
	ID_Greek_eta
	ID_Greek_theta
	ID_Greek_iota
	ID_Greek_kappa
	ID_Greek_lamda
	ID_Greek_lambda
	ID_Greek_mu
	ID_Greek_nu
	ID_Greek_xi
	ID_Greek_omicron
	ID_Greek_pi
	ID_Greek_rho
	ID_Greek_sigma
	ID_Greek_finalsmallsigma
	ID_Greek_tau
	ID_Greek_upsilon
	ID_Greek_phi
	ID_Greek_chi
	ID_Greek_psi
	ID_Greek_omega
	ID_Greek_switch
	ID_leftradical
	ID_topleftradical
	ID_horizconnector
	ID_topintegral
	ID_botintegral
	ID_vertconnector
	ID_topleftsqbracket
	ID_botleftsqbracket
	ID_toprightsqbracket
	ID_botrightsqbracket
	ID_topleftparens
	ID_botleftparens
	ID_toprightparens
	ID_botrightparens
	ID_leftmiddlecurlybrace
	ID_rightmiddlecurlybrace
	ID_topleftsummation
	ID_botleftsummation
	ID_topvertsummationconnector
	ID_botvertsummationconnector
	ID_toprightsummation
	ID_botrightsummation
	ID_rightmiddlesummation
	ID_lessthanequal
	ID_notequal
	ID_greaterthanequal
	ID_integral
	ID_therefore
	ID_variation
	ID_infinity
	ID_nabla
	ID_approximate
	ID_similarequal
	ID_ifonlyif
	ID_implies
	ID_identical
	ID_radical
	ID_includedin
	ID_includes
	ID_intersection
	ID_union
	ID_logicaland
	ID_logicalor
	ID_partialderivative
	ID_function
	ID_leftarrow
	ID_uparrow
	ID_rightarrow
	ID_downarrow
	ID_blank
	ID_soliddiamond
	ID_checkerboard
	ID_ht
	ID_ff
	ID_cr
	ID_lf
	ID_nl
	ID_vt
	ID_lowrightcorner
	ID_uprightcorner
	ID_upleftcorner
	ID_lowleftcorner
	ID_crossinglines
	ID_horizlinescan1
	ID_horizlinescan3
	ID_horizlinescan5
	ID_horizlinescan7
	ID_horizlinescan9
	ID_leftt
	ID_rightt
	ID_bott
	ID_topt
	ID_vertbar
	ID_emspace
	ID_enspace
	ID_em3space
	ID_em4space
	ID_digitspace
	ID_punctspace
	ID_thinspace
	ID_hairspace
	ID_emdash
	ID_endash
	ID_signifblank
	ID_ellipsis
	ID_doubbaselinedot
	ID_onethird
	ID_twothirds
	ID_onefifth
	ID_twofifths
	ID_threefifths
	ID_fourfifths
	ID_onesixth
	ID_fivesixths
	ID_careof
	ID_figdash
	ID_leftanglebracket
	ID_decimalpoint
	ID_rightanglebracket
	ID_marker
	ID_oneeighth
	ID_threeeighths
	ID_fiveeighths
	ID_seveneighths
	ID_trademark
	ID_signaturemark
	ID_trademarkincircle
	ID_leftopentriangle
	ID_rightopentriangle
	ID_emopencircle
	ID_emopenrectangle
	ID_leftsinglequotemark
	ID_rightsinglequotemark
	ID_leftdoublequotemark
	ID_rightdoublequotemark
	ID_prescription
	ID_minutes
	ID_seconds
	ID_latincross
	ID_hexagram
	ID_filledrectbullet
	ID_filledlefttribullet
	ID_filledrighttribullet
	ID_emfilledcircle
	ID_emfilledrect
	ID_enopencircbullet
	ID_enopensquarebullet
	ID_openrectbullet
	ID_opentribulletup
	ID_opentribulletdown
	ID_openstar
	ID_enfilledcircbullet
	ID_enfilledsqbullet
	ID_filledtribulletup
	ID_filledtribulletdown
	ID_leftpointer
	ID_rightpointer
	ID_club
	ID_diamond
	ID_heart
	ID_maltesecross
	ID_dagger
	ID_doubledagger
	ID_checkmark
	ID_ballotcross
	ID_musicalsharp
	ID_musicalflat
	ID_malesymbol
	ID_femalesymbol
	ID_telephone
	ID_telephonerecorder
	ID_phonographcopyright
	ID_caret
	ID_singlelowquotemark
	ID_doublelowquotemark
	ID_cursor
	ID_leftcaret
	ID_rightcaret
	ID_downcaret
	ID_upcaret
	ID_overbar
	ID_downtack
	ID_upshoe
	ID_downstile
	ID_underbar
	ID_jot
	ID_quad
	ID_uptack
	ID_circle
	ID_upstile
	ID_downshoe
	ID_rightshoe
	ID_leftshoe
	ID_lefttack
	ID_righttack
	ID_hebrew_doublelowline
	ID_hebrew_aleph
	ID_hebrew_bet
	ID_hebrew_beth
	ID_hebrew_gimel
	ID_hebrew_gimmel
	ID_hebrew_dalet
	ID_hebrew_daleth
	ID_hebrew_he
	ID_hebrew_waw
	ID_hebrew_zain
	ID_hebrew_zayin
	ID_hebrew_chet
	ID_hebrew_het
	ID_hebrew_tet
	ID_hebrew_teth
	ID_hebrew_yod
	ID_hebrew_finalkaph
	ID_hebrew_kaph
	ID_hebrew_lamed
	ID_hebrew_finalmem
	ID_hebrew_mem
	ID_hebrew_finalnun
	ID_hebrew_nun
	ID_hebrew_samech
	ID_hebrew_samekh
	ID_hebrew_ayin
	ID_hebrew_finalpe
	ID_hebrew_pe
	ID_hebrew_finalzade
	ID_hebrew_finalzadi
	ID_hebrew_zade
	ID_hebrew_zadi
	ID_hebrew_qoph
	ID_hebrew_kuf
	ID_hebrew_resh
	ID_hebrew_shin
	ID_hebrew_taw
	ID_hebrew_taf
	ID_Hebrew_switch
	ID_Thai_kokai
	ID_Thai_khokhai
	ID_Thai_khokhuat
	ID_Thai_khokhwai
	ID_Thai_khokhon
	ID_Thai_khorakhang
	ID_Thai_ngongu
	ID_Thai_chochan
	ID_Thai_choching
	ID_Thai_chochang
	ID_Thai_soso
	ID_Thai_chochoe
	ID_Thai_yoying
	ID_Thai_dochada
	ID_Thai_topatak
	ID_Thai_thothan
	ID_Thai_thonangmontho
	ID_Thai_thophuthao
	ID_Thai_nonen
	ID_Thai_dodek
	ID_Thai_totao
	ID_Thai_thothung
	ID_Thai_thothahan
	ID_Thai_thothong
	ID_Thai_nonu
	ID_Thai_bobaimai
	ID_Thai_popla
	ID_Thai_phophung
	ID_Thai_fofa
	ID_Thai_phophan
	ID_Thai_fofan
	ID_Thai_phosamphao
	ID_Thai_moma
	ID_Thai_yoyak
	ID_Thai_rorua
	ID_Thai_ru
	ID_Thai_loling
	ID_Thai_lu
	ID_Thai_wowaen
	ID_Thai_sosala
	ID_Thai_sorusi
	ID_Thai_sosua
	ID_Thai_hohip
	ID_Thai_lochula
	ID_Thai_oang
	ID_Thai_honokhuk
	ID_Thai_paiyannoi
	ID_Thai_saraa
	ID_Thai_maihanakat
	ID_Thai_saraaa
	ID_Thai_saraam
	ID_Thai_sarai
	ID_Thai_saraii
	ID_Thai_saraue
	ID_Thai_sarauee
	ID_Thai_sarau
	ID_Thai_sarauu
	ID_Thai_phinthu
	ID_Thai_maihanakat_maitho
	ID_Thai_baht
	ID_Thai_sarae
	ID_Thai_saraae
	ID_Thai_sarao
	ID_Thai_saraaimaimuan
	ID_Thai_saraaimaimalai
	ID_Thai_lakkhangyao
	ID_Thai_maiyamok
	ID_Thai_maitaikhu
	ID_Thai_maiek
	ID_Thai_maitho
	ID_Thai_maitri
	ID_Thai_maichattawa
	ID_Thai_thanthakhat
	ID_Thai_nikhahit
	ID_Thai_leksun
	ID_Thai_leknung
	ID_Thai_leksong
	ID_Thai_leksam
	ID_Thai_leksi
	ID_Thai_lekha
	ID_Thai_lekhok
	ID_Thai_lekchet
	ID_Thai_lekpaet
	ID_Thai_lekkao
	ID_Hangul
	ID_Hangul_Start
	ID_Hangul_End
	ID_Hangul_Hanja
	ID_Hangul_Jamo
	ID_Hangul_Romaja
	ID_Hangul_Codeinput
	ID_Hangul_Jeonja
	ID_Hangul_Banja
	ID_Hangul_PreHanja
	ID_Hangul_PostHanja
	ID_Hangul_SingleCandidate
	ID_Hangul_MultipleCandidate
	ID_Hangul_PreviousCandidate
	ID_Hangul_Special
	ID_Hangul_switch
	ID_Hangul_Kiyeog
	ID_Hangul_SsangKiyeog
	ID_Hangul_KiyeogSios
	ID_Hangul_Nieun
	ID_Hangul_NieunJieuj
	ID_Hangul_NieunHieuh
	ID_Hangul_Dikeud
	ID_Hangul_SsangDikeud
	ID_Hangul_Rieul
	ID_Hangul_RieulKiyeog
	ID_Hangul_RieulMieum
	ID_Hangul_RieulPieub
	ID_Hangul_RieulSios
	ID_Hangul_RieulTieut
	ID_Hangul_RieulPhieuf
	ID_Hangul_RieulHieuh
	ID_Hangul_Mieum
	ID_Hangul_Pieub
	ID_Hangul_SsangPieub
	ID_Hangul_PieubSios
	ID_Hangul_Sios
	ID_Hangul_SsangSios
	ID_Hangul_Ieung
	ID_Hangul_Jieuj
	ID_Hangul_SsangJieuj
	ID_Hangul_Cieuc
	ID_Hangul_Khieuq
	ID_Hangul_Tieut
	ID_Hangul_Phieuf
	ID_Hangul_Hieuh
	ID_Hangul_A
	ID_Hangul_AE
	ID_Hangul_YA
	ID_Hangul_YAE
	ID_Hangul_EO
	ID_Hangul_E
	ID_Hangul_YEO
	ID_Hangul_YE
	ID_Hangul_O
	ID_Hangul_WA
	ID_Hangul_WAE
	ID_Hangul_OE
	ID_Hangul_YO
	ID_Hangul_U
	ID_Hangul_WEO
	ID_Hangul_WE
	ID_Hangul_WI
	ID_Hangul_YU
	ID_Hangul_EU
	ID_Hangul_YI
	ID_Hangul_I
	ID_Hangul_J_Kiyeog
	ID_Hangul_J_SsangKiyeog
	ID_Hangul_J_KiyeogSios
	ID_Hangul_J_Nieun
	ID_Hangul_J_NieunJieuj
	ID_Hangul_J_NieunHieuh
	ID_Hangul_J_Dikeud
	ID_Hangul_J_Rieul
	ID_Hangul_J_RieulKiyeog
	ID_Hangul_J_RieulMieum
	ID_Hangul_J_RieulPieub
	ID_Hangul_J_RieulSios
	ID_Hangul_J_RieulTieut
	ID_Hangul_J_RieulPhieuf
	ID_Hangul_J_RieulHieuh
	ID_Hangul_J_Mieum
	ID_Hangul_J_Pieub
	ID_Hangul_J_PieubSios
	ID_Hangul_J_Sios
	ID_Hangul_J_SsangSios
	ID_Hangul_J_Ieung
	ID_Hangul_J_Jieuj
	ID_Hangul_J_Cieuc
	ID_Hangul_J_Khieuq
	ID_Hangul_J_Tieut
	ID_Hangul_J_Phieuf
	ID_Hangul_J_Hieuh
	ID_Hangul_RieulYeorinHieuh
	ID_Hangul_SunkyeongeumMieum
	ID_Hangul_SunkyeongeumPieub
	ID_Hangul_PanSios
	ID_Hangul_KkogjiDalrinIeung
	ID_Hangul_SunkyeongeumPhieuf
	ID_Hangul_YeorinHieuh
	ID_Hangul_AraeA
	ID_Hangul_AraeAE
	ID_Hangul_J_PanSios
	ID_Hangul_J_KkogjiDalrinIeung
	ID_Hangul_J_YeorinHieuh
	ID_Korean_Won
	ID_Armenian_ligature_ew
	ID_Armenian_full_stop
	ID_Armenian_verjaket
	ID_Armenian_separation_mark
	ID_Armenian_but
	ID_Armenian_hyphen
	ID_Armenian_yentamna
	ID_Armenian_exclam
	ID_Armenian_amanak
	ID_Armenian_accent
	ID_Armenian_shesht
	ID_Armenian_question
	ID_Armenian_paruyk
	ID_Armenian_AYB
	ID_Armenian_ayb
	ID_Armenian_BEN
	ID_Armenian_ben
	ID_Armenian_GIM
	ID_Armenian_gim
	ID_Armenian_DA
	ID_Armenian_da
	ID_Armenian_YECH
	ID_Armenian_yech
	ID_Armenian_ZA
	ID_Armenian_za
	ID_Armenian_E
	ID_Armenian_e
	ID_Armenian_AT
	ID_Armenian_at
	ID_Armenian_TO
	ID_Armenian_to
	ID_Armenian_ZHE
	ID_Armenian_zhe
	ID_Armenian_INI
	ID_Armenian_ini
	ID_Armenian_LYUN
	ID_Armenian_lyun
	ID_Armenian_KHE
	ID_Armenian_khe
	ID_Armenian_TSA
	ID_Armenian_tsa
	ID_Armenian_KEN
	ID_Armenian_ken
	ID_Armenian_HO
	ID_Armenian_ho
	ID_Armenian_DZA
	ID_Armenian_dza
	ID_Armenian_GHAT
	ID_Armenian_ghat
	ID_Armenian_TCHE
	ID_Armenian_tche
	ID_Armenian_MEN
	ID_Armenian_men
	ID_Armenian_HI
	ID_Armenian_hi
	ID_Armenian_NU
	ID_Armenian_nu
	ID_Armenian_SHA
	ID_Armenian_sha
	ID_Armenian_VO
	ID_Armenian_vo
	ID_Armenian_CHA
	ID_Armenian_cha
	ID_Armenian_PE
	ID_Armenian_pe
	ID_Armenian_JE
	ID_Armenian_je
	ID_Armenian_RA
	ID_Armenian_ra
	ID_Armenian_SE
	ID_Armenian_se
	ID_Armenian_VEV
	ID_Armenian_vev
	ID_Armenian_TYUN
	ID_Armenian_tyun
	ID_Armenian_RE
	ID_Armenian_re
	ID_Armenian_TSO
	ID_Armenian_tso
	ID_Armenian_VYUN
	ID_Armenian_vyun
	ID_Armenian_PYUR
	ID_Armenian_pyur
	ID_Armenian_KE
	ID_Armenian_ke
	ID_Armenian_O
	ID_Armenian_o
	ID_Armenian_FE
	ID_Armenian_fe
	ID_Armenian_apostrophe
	ID_Georgian_an
	ID_Georgian_ban
	ID_Georgian_gan
	ID_Georgian_don
	ID_Georgian_en
	ID_Georgian_vin
	ID_Georgian_zen
	ID_Georgian_tan
	ID_Georgian_in
	ID_Georgian_kan
	ID_Georgian_las
	ID_Georgian_man
	ID_Georgian_nar
	ID_Georgian_on
	ID_Georgian_par
	ID_Georgian_zhar
	ID_Georgian_rae
	ID_Georgian_san
	ID_Georgian_tar
	ID_Georgian_un
	ID_Georgian_phar
	ID_Georgian_khar
	ID_Georgian_ghan
	ID_Georgian_qar
	ID_Georgian_shin
	ID_Georgian_chin
	ID_Georgian_can
	ID_Georgian_jil
	ID_Georgian_cil
	ID_Georgian_char
	ID_Georgian_xan
	ID_Georgian_jhan
	ID_Georgian_hae
	ID_Georgian_he
	ID_Georgian_hie
	ID_Georgian_we
	ID_Georgian_har
	ID_Georgian_hoe
	ID_Georgian_fi
	ID_Xabovedot
	ID_Ibreve
	ID_Zstroke
	ID_Gcaron
	ID_Ocaron
	ID_Obarred
	ID_xabovedot
	ID_ibreve
	ID_zstroke
	ID_gcaron
	ID_ocaron
	ID_obarred
	ID_SCHWA
	ID_schwa
	ID_Lbelowdot
	ID_lbelowdot
	ID_Abelowdot
	ID_abelowdot
	ID_Ahook
	ID_ahook
	ID_Acircumflexacute
	ID_acircumflexacute
	ID_Acircumflexgrave
	ID_acircumflexgrave
	ID_Acircumflexhook
	ID_acircumflexhook
	ID_Acircumflextilde
	ID_acircumflextilde
	ID_Acircumflexbelowdot
	ID_acircumflexbelowdot
	ID_Abreveacute
	ID_abreveacute
	ID_Abrevegrave
	ID_abrevegrave
	ID_Abrevehook
	ID_abrevehook
	ID_Abrevetilde
	ID_abrevetilde
	ID_Abrevebelowdot
	ID_abrevebelowdot
	ID_Ebelowdot
	ID_ebelowdot
	ID_Ehook
	ID_ehook
	ID_Etilde
	ID_etilde
	ID_Ecircumflexacute
	ID_ecircumflexacute
	ID_Ecircumflexgrave
	ID_ecircumflexgrave
	ID_Ecircumflexhook
	ID_ecircumflexhook
	ID_Ecircumflextilde
	ID_ecircumflextilde
	ID_Ecircumflexbelowdot
	ID_ecircumflexbelowdot
	ID_Ihook
	ID_ihook
	ID_Ibelowdot
	ID_ibelowdot
	ID_Obelowdot
	ID_obelowdot
	ID_Ohook
	ID_ohook
	ID_Ocircumflexacute
	ID_ocircumflexacute
	ID_Ocircumflexgrave
	ID_ocircumflexgrave
	ID_Ocircumflexhook
	ID_ocircumflexhook
	ID_Ocircumflextilde
	ID_ocircumflextilde
	ID_Ocircumflexbelowdot
	ID_ocircumflexbelowdot
	ID_Ohornacute
	ID_ohornacute
	ID_Ohorngrave
	ID_ohorngrave
	ID_Ohornhook
	ID_ohornhook
	ID_Ohorntilde
	ID_ohorntilde
	ID_Ohornbelowdot
	ID_ohornbelowdot
	ID_Ubelowdot
	ID_ubelowdot
	ID_Uhook
	ID_uhook
	ID_Uhornacute
	ID_uhornacute
	ID_Uhorngrave
	ID_uhorngrave
	ID_Uhornhook
	ID_uhornhook
	ID_Uhorntilde
	ID_uhorntilde
	ID_Uhornbelowdot
	ID_uhornbelowdot
	ID_Ybelowdot
	ID_ybelowdot
	ID_Yhook
	ID_yhook
	ID_Ytilde
	ID_ytilde
	ID_Ohorn
	ID_ohorn
	ID_Uhorn
	ID_uhorn
	ID_EcuSign
	ID_ColonSign
	ID_CruzeiroSign
	ID_FFrancSign
	ID_LiraSign
	ID_MillSign
	ID_NairaSign
	ID_PesetaSign
	ID_RupeeSign
	ID_WonSign
	ID_NewSheqelSign
	ID_DongSign
	ID_EuroSign
	ID_zerosuperior
	ID_foursuperior
	ID_fivesuperior
	ID_sixsuperior
	ID_sevensuperior
	ID_eightsuperior
	ID_ninesuperior
	ID_zerosubscript
	ID_onesubscript
	ID_twosubscript
	ID_threesubscript
	ID_foursubscript
	ID_fivesubscript
	ID_sixsubscript
	ID_sevensubscript
	ID_eightsubscript
	ID_ninesubscript
	ID_partdifferential
	ID_emptyset
	ID_elementof
	ID_notelementof
	ID_containsas
	ID_squareroot
	ID_cuberoot
	ID_fourthroot
	ID_dintegral
	ID_tintegral
	ID_because
	ID_approxeq
	ID_notapproxeq
	ID_notidentical
	ID_stricteq
	ID_braille_dot_1
	ID_braille_dot_2
	ID_braille_dot_3
	ID_braille_dot_4
	ID_braille_dot_5
	ID_braille_dot_6
	ID_braille_dot_7
	ID_braille_dot_8
	ID_braille_dot_9
	ID_braille_dot_10
	ID_braille_blank
	ID_braille_dots_1
	ID_braille_dots_2
	ID_braille_dots_12
	ID_braille_dots_3
	ID_braille_dots_13
	ID_braille_dots_23
	ID_braille_dots_123
	ID_braille_dots_4
	ID_braille_dots_14
	ID_braille_dots_24
	ID_braille_dots_124
	ID_braille_dots_34
	ID_braille_dots_134
	ID_braille_dots_234
	ID_braille_dots_1234
	ID_braille_dots_5
	ID_braille_dots_15
	ID_braille_dots_25
	ID_braille_dots_125
	ID_braille_dots_35
	ID_braille_dots_135
	ID_braille_dots_235
	ID_braille_dots_1235
	ID_braille_dots_45
	ID_braille_dots_145
	ID_braille_dots_245
	ID_braille_dots_1245
	ID_braille_dots_345
	ID_braille_dots_1345
	ID_braille_dots_2345
	ID_braille_dots_12345
	ID_braille_dots_6
	ID_braille_dots_16
	ID_braille_dots_26
	ID_braille_dots_126
	ID_braille_dots_36
	ID_braille_dots_136
	ID_braille_dots_236
	ID_braille_dots_1236
	ID_braille_dots_46
	ID_braille_dots_146
	ID_braille_dots_246
	ID_braille_dots_1246
	ID_braille_dots_346
	ID_braille_dots_1346
	ID_braille_dots_2346
	ID_braille_dots_12346
	ID_braille_dots_56
	ID_braille_dots_156
	ID_braille_dots_256
	ID_braille_dots_1256
	ID_braille_dots_356
	ID_braille_dots_1356
	ID_braille_dots_2356
	ID_braille_dots_12356
	ID_braille_dots_456
	ID_braille_dots_1456
	ID_braille_dots_2456
	ID_braille_dots_12456
	ID_braille_dots_3456
	ID_braille_dots_13456
	ID_braille_dots_23456
	ID_braille_dots_123456
	ID_braille_dots_7
	ID_braille_dots_17
	ID_braille_dots_27
	ID_braille_dots_127
	ID_braille_dots_37
	ID_braille_dots_137
	ID_braille_dots_237
	ID_braille_dots_1237
	ID_braille_dots_47
	ID_braille_dots_147
	ID_braille_dots_247
	ID_braille_dots_1247
	ID_braille_dots_347
	ID_braille_dots_1347
	ID_braille_dots_2347
	ID_braille_dots_12347
	ID_braille_dots_57
	ID_braille_dots_157
	ID_braille_dots_257
	ID_braille_dots_1257
	ID_braille_dots_357
	ID_braille_dots_1357
	ID_braille_dots_2357
	ID_braille_dots_12357
	ID_braille_dots_457
	ID_braille_dots_1457
	ID_braille_dots_2457
	ID_braille_dots_12457
	ID_braille_dots_3457
	ID_braille_dots_13457
	ID_braille_dots_23457
	ID_braille_dots_123457
	ID_braille_dots_67
	ID_braille_dots_167
	ID_braille_dots_267
	ID_braille_dots_1267
	ID_braille_dots_367
	ID_braille_dots_1367
	ID_braille_dots_2367
	ID_braille_dots_12367
	ID_braille_dots_467
	ID_braille_dots_1467
	ID_braille_dots_2467
	ID_braille_dots_12467
	ID_braille_dots_3467
	ID_braille_dots_13467
	ID_braille_dots_23467
	ID_braille_dots_123467
	ID_braille_dots_567
	ID_braille_dots_1567
	ID_braille_dots_2567
	ID_braille_dots_12567
	ID_braille_dots_3567
	ID_braille_dots_13567
	ID_braille_dots_23567
	ID_braille_dots_123567
	ID_braille_dots_4567
	ID_braille_dots_14567
	ID_braille_dots_24567
	ID_braille_dots_124567
	ID_braille_dots_34567
	ID_braille_dots_134567
	ID_braille_dots_234567
	ID_braille_dots_1234567
	ID_braille_dots_8
	ID_braille_dots_18
	ID_braille_dots_28
	ID_braille_dots_128
	ID_braille_dots_38
	ID_braille_dots_138
	ID_braille_dots_238
	ID_braille_dots_1238
	ID_braille_dots_48
	ID_braille_dots_148
	ID_braille_dots_248
	ID_braille_dots_1248
	ID_braille_dots_348
	ID_braille_dots_1348
	ID_braille_dots_2348
	ID_braille_dots_12348
	ID_braille_dots_58
	ID_braille_dots_158
	ID_braille_dots_258
	ID_braille_dots_1258
	ID_braille_dots_358
	ID_braille_dots_1358
	ID_braille_dots_2358
	ID_braille_dots_12358
	ID_braille_dots_458
	ID_braille_dots_1458
	ID_braille_dots_2458
	ID_braille_dots_12458
	ID_braille_dots_3458
	ID_braille_dots_13458
	ID_braille_dots_23458
	ID_braille_dots_123458
	ID_braille_dots_68
	ID_braille_dots_168
	ID_braille_dots_268
	ID_braille_dots_1268
	ID_braille_dots_368
	ID_braille_dots_1368
	ID_braille_dots_2368
	ID_braille_dots_12368
	ID_braille_dots_468
	ID_braille_dots_1468
	ID_braille_dots_2468
	ID_braille_dots_12468
	ID_braille_dots_3468
	ID_braille_dots_13468
	ID_braille_dots_23468
	ID_braille_dots_123468
	ID_braille_dots_568
	ID_braille_dots_1568
	ID_braille_dots_2568
	ID_braille_dots_12568
	ID_braille_dots_3568
	ID_braille_dots_13568
	ID_braille_dots_23568
	ID_braille_dots_123568
	ID_braille_dots_4568
	ID_braille_dots_14568
	ID_braille_dots_24568
	ID_braille_dots_124568
	ID_braille_dots_34568
	ID_braille_dots_134568
	ID_braille_dots_234568
	ID_braille_dots_1234568
	ID_braille_dots_78
	ID_braille_dots_178
	ID_braille_dots_278
	ID_braille_dots_1278
	ID_braille_dots_378
	ID_braille_dots_1378
	ID_braille_dots_2378
	ID_braille_dots_12378
	ID_braille_dots_478
	ID_braille_dots_1478
	ID_braille_dots_2478
	ID_braille_dots_12478
	ID_braille_dots_3478
	ID_braille_dots_13478
	ID_braille_dots_23478
	ID_braille_dots_123478
	ID_braille_dots_578
	ID_braille_dots_1578
	ID_braille_dots_2578
	ID_braille_dots_12578
	ID_braille_dots_3578
	ID_braille_dots_13578
	ID_braille_dots_23578
	ID_braille_dots_123578
	ID_braille_dots_4578
	ID_braille_dots_14578
	ID_braille_dots_24578
	ID_braille_dots_124578
	ID_braille_dots_34578
	ID_braille_dots_134578
	ID_braille_dots_234578
	ID_braille_dots_1234578
	ID_braille_dots_678
	ID_braille_dots_1678
	ID_braille_dots_2678
	ID_braille_dots_12678
	ID_braille_dots_3678
	ID_braille_dots_13678
	ID_braille_dots_23678
	ID_braille_dots_123678
	ID_braille_dots_4678
	ID_braille_dots_14678
	ID_braille_dots_24678
	ID_braille_dots_124678
	ID_braille_dots_34678
	ID_braille_dots_134678
	ID_braille_dots_234678
	ID_braille_dots_1234678
	ID_braille_dots_5678
	ID_braille_dots_15678
	ID_braille_dots_25678
	ID_braille_dots_125678
	ID_braille_dots_35678
	ID_braille_dots_135678
	ID_braille_dots_235678
	ID_braille_dots_1235678
	ID_braille_dots_45678
	ID_braille_dots_145678
	ID_braille_dots_245678
	ID_braille_dots_1245678
	ID_braille_dots_345678
	ID_braille_dots_1345678
	ID_braille_dots_2345678
	ID_braille_dots_12345678
	ID_XF86ModeLock
	ID_XF86MonBrightnessUp
	ID_XF86MonBrightnessDown
	ID_XF86KbdLightOnOff
	ID_XF86KbdBrightnessUp
	ID_XF86KbdBrightnessDown
	ID_XF86Standby
	ID_XF86AudioLowerVolume
	ID_XF86AudioMute
	ID_XF86AudioRaiseVolume
	ID_XF86AudioPlay
	ID_XF86AudioStop
	ID_XF86AudioPrev
	ID_XF86AudioNext
	ID_XF86HomePage
	ID_XF86Mail
	ID_XF86Start
	ID_XF86Search
	ID_XF86AudioRecord
	ID_XF86Calculator
	ID_XF86Memo
	ID_XF86ToDoList
	ID_XF86Calendar
	ID_XF86PowerDown
	ID_XF86ContrastAdjust
	ID_XF86RockerUp
	ID_XF86RockerDown
	ID_XF86RockerEnter
	ID_XF86Back
	ID_XF86Forward
	ID_XF86Stop
	ID_XF86Refresh
	ID_XF86PowerOff
	ID_XF86WakeUp
	ID_XF86Eject
	ID_XF86ScreenSaver
	ID_XF86WWW
	ID_XF86Sleep
	ID_XF86Favorites
	ID_XF86AudioPause
	ID_XF86AudioMedia
	ID_XF86MyComputer
	ID_XF86VendorHome
	ID_XF86LightBulb
	ID_XF86Shop
	ID_XF86History
	ID_XF86OpenURL
	ID_XF86AddFavorite
	ID_XF86HotLinks
	ID_XF86BrightnessAdjust
	ID_XF86Finance
	ID_XF86Community
	ID_XF86AudioRewind
	ID_XF86BackForward
	ID_XF86Launch0
	ID_XF86Launch1
	ID_XF86Launch2
	ID_XF86Launch3
	ID_XF86Launch4
	ID_XF86Launch5
	ID_XF86Launch6
	ID_XF86Launch7
	ID_XF86Launch8
	ID_XF86Launch9
	ID_XF86LaunchA
	ID_XF86LaunchB
	ID_XF86LaunchC
	ID_XF86LaunchD
	ID_XF86LaunchE
	ID_XF86LaunchF
	ID_XF86ApplicationLeft
	ID_XF86ApplicationRight
	ID_XF86Book
	ID_XF86CD
	ID_XF86Calculater
	ID_XF86Clear
	ID_XF86Close
	ID_XF86Copy
	ID_XF86Cut
	ID_XF86Display
	ID_XF86DOS
	ID_XF86Documents
	ID_XF86Excel
	ID_XF86Explorer
	ID_XF86Game
	ID_XF86Go
	ID_XF86iTouch
	ID_XF86LogOff
	ID_XF86Market
	ID_XF86Meeting
	ID_XF86MenuKB
	ID_XF86MenuPB
	ID_XF86MySites
	ID_XF86New
	ID_XF86News
	ID_XF86OfficeHome
	ID_XF86Open
	ID_XF86Option
	ID_XF86Paste
	ID_XF86Phone
	ID_XF86Q
	ID_XF86Reply
	ID_XF86Reload
	ID_XF86RotateWindows
	ID_XF86RotationPB
	ID_XF86RotationKB
	ID_XF86Save
	ID_XF86ScrollUp
	ID_XF86ScrollDown
	ID_XF86ScrollClick
	ID_XF86Send
	ID_XF86Spell
	ID_XF86SplitScreen
	ID_XF86Support
	ID_XF86TaskPane
	ID_XF86Terminal
	ID_XF86Tools
	ID_XF86Travel
	ID_XF86UserPB
	ID_XF86User1KB
	ID_XF86User2KB
	ID_XF86Video
	ID_XF86WheelButton
	ID_XF86Word
	ID_XF86Xfer
	ID_XF86ZoomIn
	ID_XF86ZoomOut
	ID_XF86Away
	ID_XF86Messenger
	ID_XF86WebCam
	ID_XF86MailForward
	ID_XF86Pictures
	ID_XF86Music
	ID_XF86Battery
	ID_XF86Bluetooth
	ID_XF86WLAN
	ID_XF86UWB
	ID_XF86AudioForward
	ID_XF86AudioRepeat
	ID_XF86AudioRandomPlay
	ID_XF86Subtitle
	ID_XF86AudioCycleTrack
	ID_XF86CycleAngle
	ID_XF86FrameBack
	ID_XF86FrameForward
	ID_XF86Time
	ID_XF86Select
	ID_XF86View
	ID_XF86TopMenu
	ID_XF86Red
	ID_XF86Green
	ID_XF86Yellow
	ID_XF86Blue
	ID_XF86Suspend
	ID_XF86Hibernate
	ID_XF86TouchpadToggle
	ID_XF86TouchpadOn
	ID_XF86TouchpadOff
	ID_XF86AudioMicMute
	ID_XF86Switch_VT_1
	ID_XF86Switch_VT_2
	ID_XF86Switch_VT_3
	ID_XF86Switch_VT_4
	ID_XF86Switch_VT_5
	ID_XF86Switch_VT_6
	ID_XF86Switch_VT_7
	ID_XF86Switch_VT_8
	ID_XF86Switch_VT_9
	ID_XF86Switch_VT_10
	ID_XF86Switch_VT_11
	ID_XF86Switch_VT_12
	ID_XF86Ungrab
	ID_XF86ClearGrab
	ID_XF86Next_VMode
	ID_XF86Prev_VMode
	ID_XF86LogWindowTree
	ID_XF86LogGrabInfo
)
