name: Build runify

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'server/go.mod'
          check-latest: false
          cache: true
          cache-dependency-path: server/go.sum

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'

      - name: Setup deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev
          version: 1.0

      - name: Build server
        working-directory: ./server
        run: make build

      - name: Check server version
        working-directory: ./server
        run: ./runify-server version

      - name: Build UI
        working-directory: ./ui
        run: make build_release
