name: Build runify

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'server/go.mod'
          check-latest: false
          cache: true
          cache-dependency-path: server/go.sum

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          architecture: x64

      - name: Setup deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ninja-build libgtk-3-dev
          version: 1.0

      - name: Show env
        run: env

      - name: Build UI and server
        run: make release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: runify
          path: release/
